export {
  acquirePowerKeepAwake,
  attachPower,
  createPower,
  destroyPowerKeepAwake,
  detachPower,
  disposePower,
  enablePowerSignals,
  getPowerBatteryHealth,
  getPowerIdlePollingIntervalMs,
  getPowerStatus,
  getPowerSystemIdleState,
  getPowerSystemIdleTime,
  getPowerThermalState,
  isPowerKeepAwakeActive,
  makePowerBatteryHealth,
  makePowerStatus,
  releasePowerKeepAwake,
  setPowerIdlePollingIntervalMs,
} from './contract';
