export {
  attachPower,
  createPower,
  detachPower,
  disposePower,
  enablePowerSignals,
  getPowerBatteryHealth,
  getPowerIdlePollingIntervalMs,
  getPowerStatus,
  getPowerSystemIdleState,
  getPowerSystemIdleTime,
  getPowerThermalState,
  hasPowerKeepAwake,
  setPowerIdlePollingIntervalMs,
  setPowerKeepAwake,
} from './contract';
