import { enableHostWebAccessibility } from './webAccessibility';
import { enableHostWebAudio } from './webAudio';
import { enableHostWebAudioDevice } from './webAudioDevice';
import { enableHostWebBitmapEncode } from './webBitmapEncode';
import { enableHostWebClipboard } from './webClipboard';
import { enableHostWebConnectivity } from './webConnectivity';
import { enableHostWebDevice } from './webDevice';
import { enableHostWebDialog } from './webDialog';
import { enableHostWebFileSystem } from './webFilesystem';
import { enableHostWebFontLoading } from './webFontLoading';
import { enableHostWebGeolocation } from './webGeolocation';
import { enableHostWebGlyphRasterizer } from './webGlyphRasterizer';
import { enableHostWebHaptics } from './webHaptics';
import { enableHostWebImage } from './webImage';
import { enableHostWebSoftKeyboard } from './webKeyboard';
import { enableHostWebLifecycle } from './webLifecycle';
import { enableHostWebLoop } from './webLoop';
import { enableHostWebMediaSession } from './webMediasession';
import { enableHostWebNotification } from './webNotification';
import { enableHostWebPermission } from './webPermissions';
import { enableHostWebPlatform } from './webPlatform';
import { enableHostWebScreen } from './webScreen';
import { enableHostWebSensors } from './webSensors';
import { enableHostWebShare } from './webShare';
import { enableHostWebStorage } from './webStorage';
import { enableHostWebVideoCapability } from './webVideoCapability';
import { enableHostWebWebcam } from './webWebcam';

export function enableHostWeb(): void {
  enableHostWebAccessibility();
  enableHostWebAudio();
  enableHostWebAudioDevice();
  enableHostWebBitmapEncode();
  enableHostWebClipboard();
  enableHostWebConnectivity();
  enableHostWebDevice();
  enableHostWebDialog();
  enableHostWebFileSystem();
  enableHostWebFontLoading();
  enableHostWebGeolocation();
  enableHostWebGlyphRasterizer();
  enableHostWebHaptics();
  enableHostWebImage();
  enableHostWebSoftKeyboard();
  enableHostWebLifecycle();
  enableHostWebLoop();
  enableHostWebMediaSession();
  enableHostWebNotification();
  enableHostWebPermission();
  enableHostWebPlatform();
  enableHostWebScreen();
  enableHostWebSensors();
  enableHostWebShare();
  enableHostWebStorage();
  enableHostWebVideoCapability();
  enableHostWebWebcam();
}
