import { enableHostWebAccessibility } from './webAccessibility';
import { enableHostWebAudio } from './webAudio';
import { enableHostWebAudioDevice } from './webAudioDevice';
import { enableHostWebBitmapEncode } from './webBitmapEncode';
import { enableHostWebBitmapReadback } from './webBitmapReadback';
import { enableHostWebConnectivity } from './webConnectivity';
import { enableHostWebDevice } from './webDevice';
import { enableHostWebFileSystem } from './webFilesystem';
import { enableHostWebFontLoading } from './webFontLoading';
import { enableHostWebGeolocation } from './webGeolocation';
import { enableHostWebGlyphRasterizer } from './webGlyphRasterizer';
import { enableHostWebImage } from './webImage';
import { enableHostWebSoftKeyboard } from './webKeyboard';
import { enableHostWebLifecycle } from './webLifecycle';
import { enableHostWebMediaSession } from './webMediasession';
import { enableHostWebPermission } from './webPermissions';
import { enableHostWebPlatform } from './webPlatform';
import { enableHostWebRaster2DSurface } from './webRaster2DSurface';
import { enableHostWebScreen } from './webScreen';
import { enableHostWebSensors } from './webSensors';
import { enableHostWebStorage } from './webStorage';
import { enableHostWebVideoCapability } from './webVideoCapability';
import { enableHostWebWebcam } from './webWebcam';

export function enableHostWeb(): void {
  enableHostWebAccessibility();
  enableHostWebAudio();
  enableHostWebAudioDevice();
  enableHostWebBitmapEncode();
  enableHostWebBitmapReadback();
  enableHostWebConnectivity();
  enableHostWebDevice();
  enableHostWebFileSystem();
  enableHostWebFontLoading();
  enableHostWebGeolocation();
  enableHostWebGlyphRasterizer();
  enableHostWebImage();
  enableHostWebSoftKeyboard();
  enableHostWebLifecycle();
  enableHostWebMediaSession();
  enableHostWebPermission();
  enableHostWebPlatform();
  enableHostWebRaster2DSurface();
  enableHostWebScreen();
  enableHostWebSensors();
  enableHostWebStorage();
  enableHostWebVideoCapability();
  enableHostWebWebcam();
}
