import type { RequirementCatalogEntry } from '@flighthq/types/contract';

// GENERATED by `npm run catalog` from scripts/catalog.ts. DO NOT EDIT BY HAND.
// Stage 4 builds the mechanism only; built-in ownership rows remain deliberately unpopulated.
export const BUILT_IN_REQUIREMENT_CATALOG_ENTRIES: readonly RequirementCatalogEntry[] = [];
