export {
  computeBitmapTextLocalBoundsRectangle,
  createBitmapText,
  createBitmapTextData,
  getBitmapTextBounds,
  getBitmapTextPages,
  reserveBitmapText,
  setBitmapTextAlign,
  setBitmapTextGlyphSource,
  setBitmapTextLetterSpacing,
  setBitmapTextLineHeight,
  setBitmapTextText,
  setBitmapTextWrapWidth,
  updateBitmapText,
} from './contract';
