export {
  computeBitmapTextLocalBoundsRectangle,
  createBitmapText,
  disableBitmapTextGuards,
  enableBitmapTextGuards,
  explainBitmapTextMissingGlyphs,
  getBitmapTextBounds,
  getBitmapTextLineCount,
  getBitmapTextPages,
  isBitmapTextGlyphLayoutStale,
  isBitmapTextTruncated,
  refreshBitmapTextGlyphLayout,
  reserveBitmapText,
  setBitmapTextAlign,
  setBitmapTextEllipsis,
  setBitmapTextGlyphSource,
  setBitmapTextMissingGlyphGuard,
  setBitmapTextLetterSpacing,
  setBitmapTextLineHeight,
  setBitmapTextMaxLines,
  setBitmapTextText,
  setBitmapTextWrapWidth,
  updateBitmapText,
} from './contract';
