export {
  MAX_INDEXED_CELLS_PER_OBJECT,
  clearSpatialIndex2D,
  createSpatialIndex2D,
  createUniformGridSpatialBackend2D,
  explainSpatialIndexing2D,
  formatSpatialIndexingNotice,
  insertSpatialObject2D,
  querySpatialPairs2D,
  querySpatialPoint2D,
  querySpatialRay2D,
  querySpatialRegion2D,
  removeSpatialObject2D,
  setSpatialIndexingGuard,
  updateSpatialObject2D,
} from './contract';
