import type { RequirementCatalogEntry } from '@flighthq/types/contract';

import { PARSER_HANDLER_FIELDS, REQUIREMENT_OPTION_FIELDS } from './requirementOptionFields';

/** The backends a manifest module always exports a fragment for, and the export name each one uses. */
export const MANIFEST_BACKEND_EXPORTS: Readonly<Record<string, string>> = Object.freeze({
  canvas: 'canvasOptions',
  dom: 'domOptions',
  gl: 'glOptions',
  wgpu: 'wgpuOptions',
});

/**
 * The catalog backend whose rows become `parserOptions` rather than a render-state fragment.
 *
 * A row's DESTINATION is its backend, not its facet: the same `document.format` requirement resolves
 * to a tag handler for the parser and to a node renderer for `canvas`, and only the catalog author
 * knows which row is which. Routing by facet alone would send both to the same place.
 */
export const MANIFEST_PARSER_BACKEND = 'parser';

/** One resolved row: the catalog entry, and the requirement kind it satisfies. */
export interface ManifestModuleEntry {
  readonly entry: Readonly<RequirementCatalogEntry>;
  readonly kind: string;
}

/**
 * Emits the per-file manifest module for one content file.
 *
 * Flat named exports — `canvasOptions`, `glOptions`, `wgpuOptions`, `domOptions`, `parserOptions` — so
 * an application writes `import { glOptions } from './asset.swf?manifest'` and spreads it straight
 * into `createGlRenderState`. Flat flat named bindings are what make the module shakable: a bundler
 * that sees only `glOptions` imported can drop every other fragment AND the implementation modules
 * only they referenced, which it could not do if the fragments hung off one default object.
 *
 * Every referenced symbol gets a precise named import from the module the catalog row names. There is
 * no barrel import and no dynamic lookup, so the import graph states exactly which implementations
 * this one file needs.
 *
 * Deterministic: imports are grouped by module with modules and symbols sorted, map entries are
 * emitted in sorted kind order, and array entries keep catalog order. The same inputs always produce
 * byte-identical source.
 */
export function generateManifestModuleSource(rows: readonly ManifestModuleEntry[], extension: string): string {
  const importsByModule = new Map<string, Set<string>>();
  const byBackend = new Map<string, ManifestModuleEntry[]>();
  const parserRows: ManifestModuleEntry[] = [];

  for (const row of rows) {
    if (row.entry.backend === MANIFEST_PARSER_BACKEND) {
      addImport(importsByModule, row.entry.implementationImport, row.entry.implementationSymbol);
      parserRows.push(row);
      continue;
    }
    // A render-backend row needs a field to land in. A facet with no render-state field — a parser-only
    // concern aimed at a backend — is skipped here and reported by the caller rather than emitted into
    // a field that does not exist.
    if (REQUIREMENT_OPTION_FIELDS[row.entry.facet] === undefined) continue;
    addImport(importsByModule, row.entry.implementationImport, row.entry.implementationSymbol);
    let list = byBackend.get(row.entry.backend);
    if (list === undefined) {
      list = [];
      byBackend.set(row.entry.backend, list);
    }
    list.push(row);
  }

  const lines: string[] = [
    '// GENERATED by @flighthq/vite-plugin-manifest. Do not edit.',
    `// Requirements of one ${extension} file, resolved for every backend in the catalog.`,
  ];
  const importLines = [...importsByModule.keys()]
    .sort()
    .map((module) => `import { ${[...importsByModule.get(module)!].sort().join(', ')} } from '${module}';`);
  if (importLines.length > 0) lines.push('', ...importLines);

  for (const backend of Object.keys(MANIFEST_BACKEND_EXPORTS).sort()) {
    lines.push('', ...backendFragment(MANIFEST_BACKEND_EXPORTS[backend], byBackend.get(backend) ?? []));
  }
  lines.push('', ...parserFragment(parserRows, PARSER_HANDLER_FIELDS[extension] ?? 'handlers'));
  return `${lines.join('\n')}\n`;
}

function addImport(importsByModule: Map<string, Set<string>>, module: string, symbol: string): void {
  let symbols = importsByModule.get(module);
  if (symbols === undefined) {
    symbols = new Set();
    importsByModule.set(module, symbols);
  }
  symbols.add(symbol);
}

function backendFragment(exportName: string, rows: readonly ManifestModuleEntry[]): string[] {
  const byField = new Map<string, ManifestModuleEntry[]>();
  for (const row of rows) {
    const field = REQUIREMENT_OPTION_FIELDS[row.entry.facet]!;
    let list = byField.get(field);
    if (list === undefined) {
      list = [];
      byField.set(field, list);
    }
    list.push(row);
  }
  // An empty fragment is still exported. A backend this content needs nothing for must spread to
  // nothing rather than fail to import, so an application can spread every fragment unconditionally.
  if (byField.size === 0) return [`export const ${exportName} = {};`];

  const fields = [...byField.keys()].sort().map((field) => {
    const entries = [...byField.get(field)!]
      .sort((a, b) => a.kind.localeCompare(b.kind))
      .map((row) => `    ['${row.kind}', ${row.entry.implementationSymbol}],`);
    return `  ${field}: new Map([\n${entries.join('\n')}\n  ]),`;
  });
  return [`export const ${exportName} = {`, ...fields, '};'];
}

function parserFragment(rows: readonly ManifestModuleEntry[], field: string): string[] {
  if (rows.length === 0) return ['export const parserOptions = {};'];
  // Catalog order is preserved rather than sorted: a handler list is ordered, and reordering it
  // changes which handler claims a contested tag and whether AWD2's build phases see their inputs.
  const handlers = rows.map((row) => `    ${row.entry.implementationSymbol},`);
  return [`export const parserOptions = {`, `  ${field}: [`, ...handlers, '  ],', '};'];
}
