import type { RequirementCodegenPlan } from '@flighthq/types/contract';

/**
 * Emits the registration module for one codegen plan.
 *
 * `createRequirementCodegenPlan` is deliberately emission-neutral — it resolves ownership rows and
 * reports gaps but chooses no source text. Choosing that text is this package's job, and it is the
 * only place in the pipeline that knows the answer is an ES module a bundler will tree-shake.
 *
 * What makes the output shakable is that it imports exactly the registrars the plan resolved and calls
 * each one by name. There is no table of every registrar, no dynamic lookup, and no default export: a
 * bundler can see statically that an unregistered feature's module is unreachable.
 *
 * Output is DETERMINISTIC. Imports are grouped by module and both the modules and the symbols within
 * them are sorted, so the same plan always produces byte-identical source — which is what lets Vite
 * skip a rebuild and what makes a diff of generated output reviewable.
 */
export function generateRequirementModuleSource(plan: Readonly<RequirementCodegenPlan>): string {
  const registrarsByModule = new Map<string, Set<string>>();
  const calls: string[] = [];
  for (const entry of plan.entries) {
    let symbols = registrarsByModule.get(entry.registrarImport);
    if (symbols === undefined) {
      symbols = new Set();
      registrarsByModule.set(entry.registrarImport, symbols);
    }
    symbols.add(entry.registrarSymbol);
    calls.push(`${entry.registrarSymbol}(state);`);
  }

  const importLines = [...registrarsByModule.keys()]
    .sort()
    .map((module) => `import { ${[...registrarsByModule.get(module)!].sort().join(', ')} } from '${module}';`);
  const callLines = [...new Set(calls)].sort();

  // A plan that resolved nothing still emits a valid module with a working function. The alternative —
  // failing to emit — would turn "this content needs no registration" into a build error.
  const body =
    callLines.length === 0
      ? '  // No requirement in the scanned content resolved to a registrar.\n'
      : `${callLines.map((call) => `  ${call}`).join('\n')}\n`;

  return `${[
    '// GENERATED by @flighthq/vite-plugin-manifest. Do not edit.',
    `// Backend: ${plan.backend}. ${plan.entries.length} registration(s) from the scanned content.`,
    ...(importLines.length > 0 ? ['', ...importLines] : []),
    '',
    'export function registerScannedRequirements(state) {',
    body.replace(/\n$/u, ''),
    '}',
  ].join('\n')}\n`;
}
