export {
  attachGlobalShortcut,
  createGlobalShortcut,
  destroyShortcutTrigger,
  detachGlobalShortcut,
  disposeGlobalShortcut,
  equalsAccelerator,
  findAcceleratorConflict,
  formatAcceleratorForDisplay,
  getAcceleratorKey,
  getAcceleratorKeyLabel,
  getAcceleratorModifierLabel,
  getAcceleratorModifiers,
  queryGlobalShortcutConflict,
  isAcceleratorValid,
  queryGlobalShortcutRegistration,
  makeParsedAccelerator,
  normalizeAccelerator,
  parseAccelerator,
  parseAcceleratorDetailed,
  resolveCommandOrControlModifier,
} from './contract';
