export {
  acquirePathMesh,
  acquirePathMeshTyped,
  appendPathArc,
  appendPathArcTo,
  appendPathCircle,
  appendPathClose,
  appendPathCubicCurveTo,
  appendPathCurveTo,
  appendPathEllipse,
  appendPathLineTo,
  appendPathMoveTo,
  appendPathPolygon,
  appendPathPolyline,
  appendPathRectangle,
  appendPathRoundRectangle,
  cleanPath,
  clonePath,
  containsPathPoint,
  copyPath,
  createPath,
  createPathMorph,
  dashPath,
  decimatePath,
  explainPathMorphCreation,
  explainStrokePathTessellation,
  fitPathCurves,
  flattenPath,
  forEachPathSegment,
  getCubicBezierCurvature,
  getCubicBezierPoint,
  getCubicBezierTangent,
  getPathBounds,
  getPathContourLengths,
  getPathContourOrientation,
  getPathCurvatureAtDistance,
  getPathLastPoint,
  getPathLength,
  getPathNearestPoint,
  getPathPointAtDistance,
  getPathPositionAtDistance,
  getPathSegmentCurvatureAtParameter,
  getPathSegmentPointAtParameter,
  getPathSegmentTangentAtParameter,
  getPathSignedArea,
  getPathTangentAtDistance,
  getQuadraticBezierCurvature,
  getQuadraticBezierPoint,
  getQuadraticBezierTangent,
  releasePathMesh,
  releasePathMeshTyped,
  reversePath,
  samplePathMorph,
  strokePath,
  tessellatePath,
  tessellatePathInto,
  tessellatePathTyped,
  tessellatePathTypedInto,
  tessellateStrokePath,
  transformPath,
  translatePath,
} from './contract';

export type {
  PathMorph,
  PathMorphCreationExplanation,
  PathMorphCreationReason,
  StrokePathTessellationExplanation,
  StrokePathTessellationReason,
} from './contract';

// Types leave through their own `export type` line: a type named in the value block above
// compiles away in `contract.ts` but survives as a real named re-export here, so a consumer loading
// this module as untranspiled ESM asks for a binding that does not exist.
export type { StrokeStyle } from './contract';
