export {
  canPlayVideoType,
  createVideoResource,
  destroyVideoResource,
  detectVideoMimeType,
  disposeVideoResource,
  getVideoResourceDuration,
  getVideoResourceHeight,
  getVideoResourceWidth,
  hasVideoResourceElement,
  inferVideoMimeType,
  isVideoResourceEmpty,
  isVideoResourceReady,
  loadVideoResourceFromBlob,
  loadVideoResourceFromUrl,
  loadVideoResourceFromUrls,
  selectVideoResourceUrl,
} from './contract';
