export {
  attachSoftKeyboard,
  createSoftKeyboard,
  detachSoftKeyboard,
  disposeSoftKeyboard,
  getSoftKeyboardHeight,
  getSoftKeyboardInfo,
  hideSoftKeyboard,
  isSoftKeyboardVisible,
  setSoftKeyboardAccessoryBarVisible,
  setSoftKeyboardResizeMode,
  setSoftKeyboardScrollAssistEnabled,
  setSoftKeyboardStyle,
  showSoftKeyboard,
} from './contract';
