export {
  appendParticleEmitter2DParticle,
  appendParticleEmitter3DParticle,
  clearParticleEmitter2D,
  clearParticleEmitter3D,
  cloneParticleEmitter2D,
  cloneParticleEmitter3D,
  compactParticleEmitter2D,
  compactParticleEmitter3D,
  computeParticleEmitter2DLocalBoundsRectangle,
  computeParticleEmitter3DLocalBoundsAabb,
  createParticleEmitter2D,
  createParticleEmitter3D,
  emitParticleBurst2D,
  emitParticleBurst3D,
  getParticleEmitter2DCapacity,
  getParticleEmitter2DParticleAlpha,
  getParticleEmitter2DParticleId,
  getParticleEmitter2DParticleVelocity,
  getParticleEmitter3DCapacity,
  getParticleEmitter3DParticleAlpha,
  getParticleEmitter3DParticleId,
  getParticleEmitter3DParticleVelocity,
  isParticleEmitter2DComplete,
  isParticleEmitter3D,
  isParticleEmitter3DComplete,
  prewarmParticleEmitter2D,
  prewarmParticleEmitter3D,
  removeParticleEmitter2DParticle,
  removeParticleEmitter3DParticle,
  reserveParticleEmitter2D,
  reserveParticleEmitter3D,
  setParticleEmitter2DLocalBoundsRectangle,
  setParticleEmitter2DParticle,
  setParticleEmitter2DParticleAlpha,
  setParticleEmitter2DParticleColor,
  setParticleEmitter2DParticleVelocity,
  setParticleEmitter3DParticle,
  setParticleEmitter3DParticleAlpha,
  setParticleEmitter3DParticleColor,
  setParticleEmitter3DParticleVelocity,
  sortParticleEmitter3DIndicesByViewDepth,
  stepParticleEmitter2D,
  stepParticleEmitter3D,
  updateParticleEmitter2D,
  updateParticleEmitter3D,
} from './contract';

// Types leave through their own `export type` line: a type named in the value block above
// compiles away in `contract.ts` but survives as a real named re-export here, so a consumer loading
// this module as untranspiled ESM asks for a binding that does not exist.
export type { ParticleEmitterCallbacks } from './contract';
