export {
  attachProtocolHandler,
  createProtocolHandler,
  createProtocolUrl,
  detachProtocolHandler,
  disposeProtocolHandler,
  explainProtocolBackend,
  getProtocolLaunchUrl,
  getRegisteredProtocolSchemes,
  isProtocolSchemeDefault,
  isProtocolSchemeRegistered,
  isValidProtocolScheme,
  parseProtocolUrl,
  registerProtocolScheme,
  registerProtocolSchemes,
  removeProtocolSchemeAsDefault,
  setProtocolSchemeAsDefault,
  unregisterProtocolScheme,
  unregisterProtocolSchemes,
} from './contract';
