export {
  cancelScheduledNotification,
  closeAllNotifications,
  closeNotification,
  getActiveNotifications,
  getNotificationPermission,
  getPendingNotifications,
  onNotificationAction,
  onNotificationClick,
  onNotificationDismiss,
  onNotificationReply,
  onNotificationShow,
  requestNotificationPermission,
  scheduleNotification,
  showNotification,
  updateNotification,
} from './contract';
