import type { ParticleEmitterConfig } from '@flighthq/types';

export function createParticleEmitterConfig(config?: Partial<ParticleEmitterConfig>): ParticleEmitterConfig {
  return {
    alphaCurve: config?.alphaCurve ?? null,
    alphaEnd: config?.alphaEnd ?? 0,
    alphaStart: config?.alphaStart ?? 1,
    blendMode: config?.blendMode ?? null,
    burstCount: config?.burstCount ?? 0,
    burstInterval: config?.burstInterval ?? 0,
    colorCurve: config?.colorCurve ?? null,
    colorEndB: config?.colorEndB ?? 1,
    colorEndG: config?.colorEndG ?? 1,
    colorEndR: config?.colorEndR ?? 1,
    colorEndVarianceB: config?.colorEndVarianceB ?? 0,
    colorEndVarianceG: config?.colorEndVarianceG ?? 0,
    colorEndVarianceR: config?.colorEndVarianceR ?? 0,
    colorStartB: config?.colorStartB ?? 1,
    colorStartG: config?.colorStartG ?? 1,
    colorStartR: config?.colorStartR ?? 1,
    colorStartVarianceB: config?.colorStartVarianceB ?? 0,
    colorStartVarianceG: config?.colorStartVarianceG ?? 0,
    colorStartVarianceR: config?.colorStartVarianceR ?? 0,
    directionX: config?.directionX ?? 0,
    directionY: config?.directionY ?? -1,
    directionZ: config?.directionZ ?? 0,
    duration: config?.duration ?? 0,
    emitterConeAngle: config?.emitterConeAngle ?? 0,
    emitterDepth: config?.emitterDepth ?? 0,
    emitterHeight: config?.emitterHeight ?? 0,
    emitterRadius: config?.emitterRadius ?? 0,
    emitterShape: config?.emitterShape ?? 'point',
    emitterWidth: config?.emitterWidth ?? 0,
    frameCount: config?.frameCount ?? 1,
    frameRate: config?.frameRate ?? 12,
    gravityX: config?.gravityX ?? 0,
    gravityY: config?.gravityY ?? 0,
    gravityZ: config?.gravityZ ?? 0,
    lifetimeMax: config?.lifetimeMax ?? 1,
    lifetimeMin: config?.lifetimeMin ?? 0.5,
    loop: config?.loop ?? true,
    maxParticles: config?.maxParticles ?? 1000,
    regionIdMax: config?.regionIdMax ?? 1,
    regionIdMin: config?.regionIdMin ?? 0,
    rotationSpeedMax: config?.rotationSpeedMax ?? 0,
    rotationSpeedMin: config?.rotationSpeedMin ?? 0,
    scaleCurve: config?.scaleCurve ?? null,
    scaleEnd: config?.scaleEnd ?? 1,
    scaleMax: config?.scaleMax ?? 1,
    scaleMin: config?.scaleMin ?? 1,
    spawnRate: config?.spawnRate ?? 10,
    speedMax: config?.speedMax ?? 100,
    speedMin: config?.speedMin ?? 50,
    spread: config?.spread ?? Math.PI,
    velocityInheritance: config?.velocityInheritance ?? 0,
    worldSpace: config?.worldSpace ?? false,
  };
}
