export {
  canPlayAudioType,
  cloneAudioResource,
  createAudioResource,
  createAudioResourceFromSamples,
  detectAudioMimeType,
  disposeAudioResource,
  getAudioResourceByteSize,
  getAudioResourceChannelCount,
  getAudioResourceChannelData,
  getAudioResourceDuration,
  getAudioResourceSampleRate,
  hasAudioResourceBuffer,
  inferAudioMimeType,
  isAudioResourceEmpty,
  loadAudioResourceFromBase64,
  loadAudioResourceFromBlob,
  loadAudioResourceFromBytes,
  loadAudioResourceFromUrl,
  loadAudioResourceFromUrls,
  selectAudioResourceUrl,
} from './contract';
