import type { CollisionColliderShape3D } from './Collision';
import type { SpatialIndexBackend3D } from './Spatial';

// 3D rigid-body dynamics header. `@flighthq/physics3d` owns integration and constraint resolution in
// three dimensions and owns no detection of its own. Everything here is plain data advanced by an
// explicit `stepPhysics3D(world, dt)` — no implicit world object, no hidden per-frame allocation, and
// no scene-graph reference. Copying a body's transform onto a scene node is the caller's job.
//
// 2D rigid-body dynamics is `@flighthq/physics2d`, a separate package, because the dimension changes
// the model rather than only its width: a 2D rotational inertia is one scalar about a fixed axis,
// where 3D needs a tensor that must be re-expressed in world space every step; friction acts along one
// tangent in 2D and spans a two-dimensional plane in 3D; and orientation integrates as a quaternion
// rather than accumulating into a scalar angle.
//
// Contacts are GENERATED by the step, from the colliders a body carries: the world publishes body
// bounds to a `SpatialIndexBackend3D` broadphase and resolves each candidate pair through
// `@flighthq/collision`'s 3D narrow phase. A caller may still build a `Physics3DContact` by hand and
// push it, because the solver is defined against contact records rather than against a detector — but
// that is the escape hatch, not the path. See `agents/collision-support-registry.md` and
// `agents/spatial-dimension-seams.md`.

// How a body participates in the simulation. `dynamic` is integrated by forces and resolved by
// constraints. `static` never moves and behaves as infinite mass; it is the ground, the terrain. A
// `kinematic` body is moved by the caller through its velocity and pushes dynamic bodies without being
// pushed back — a lift, a scripted door. Static and kinematic bodies both carry zero inverse mass and a
// zero inverse inertia tensor, so the solver applies no impulse to them and two of them in contact
// generate no constraint at all.
export type Physics3DBodyType = 'dynamic' | 'kinematic' | 'static';

// The surface properties a contact between two bodies is resolved with.
//
// `density` is mass per unit VOLUME — the 2D package's is per unit area, and the difference is not
// cosmetic: the same number describes a different material in each, so a density copied between them
// is wrong by a length. `friction` is the Coulomb coefficient and `restitution` the normal-direction
// bounce, both in [0,1] by convention though neither is clamped: a restitution above 1 adds energy,
// which is occasionally what a game wants and is never what a solver can promise to keep stable.
export interface Physics3DMaterial {
  density: number;
  friction: number;
  restitution: number;
}

// Which other bodies one body may contact. Categories and masks use the familiar symmetric rule: A's
// mask must include B's category AND B's mask must include A's category. A matching non-zero group
// overrides both masks — positive always collides, negative never collides — for assemblies whose
// pieces must make one decision regardless of their ordinary categories.
export interface Physics3DCollisionFilter {
  categoryBits: number;
  maskBits: number;
  groupIndex: number;
}

// One piece of collision geometry attached to a body. A body carries a LIST of these, which is what
// makes a compound body — a crate with a rubber bumper, a character with a separate head volume —
// expressible without a joint holding two bodies together.
//
// The material and the filter live HERE rather than on the body, and that placement is the whole reason
// the type exists. A body-level material forces every piece of a compound body to share one friction
// and one restitution, so the bumper cannot be bouncier than the crate; a body-level filter forces every
// piece to share one category, so the head volume cannot be queried apart from the torso. Both are
// ordinary things to build, and both are unrepresentable if these fields sit one level up.
//
// Built-in shapes only, matching `Physics2DCollider` and for the same reason: this package clones a
// collider's shape, transforms it local-to-world by kind, derives its bounds, and generates contacts for
// it — none of which a vendor kind can answer, because only the function registered for that kind knows
// what its parameters mean. The convex built-ins carry mass; triangle mesh and heightfield are static
// surfaces with no mass contribution and are rejected on dynamic or kinematic bodies. A vendor shape
// still reaches `testCollision3D` through the registries; it does not become a rigid body here.
export interface Physics3DCollider {
  // The authored shape, in the body's LOCAL frame.
  local: CollisionColliderShape3D;
  // The world-space shape, rewritten every step. Its KIND may differ from `local`'s: a rotated
  // axis-aligned box is not an axis-aligned box, so an `aabb` local shape carries a `box` world shape.
  // The alternative — forbidding aabb colliders on rotating bodies — would make a legal authoring choice
  // depend on a runtime property, and would fail silently the first time a body was given angular
  // velocity. Local kind is what you author; world kind is what the narrow phase needs.
  world: CollisionColliderShape3D;
  material: Physics3DMaterial;
  filter: Physics3DCollisionFilter;
  // A sensor reports its overlaps through the contact events and generates no impulse: a trigger volume.
  sensor: boolean;
}

// The mass properties of a body or of one primitive contributing to it.
//
// The rotational inertia is a symmetric 3x3 tensor, stored as its six unique components because a
// symmetric matrix has six and storing nine invites the two halves to disagree. `xx`/`yy`/`zz` are the
// diagonal and `xy`/`xz`/`yz` the off-diagonal terms; the tensor is expressed about the CENTRE OF MASS
// in the body's LOCAL frame, which is the only frame in which it is constant. (`centerX`,`centerY`,
// `centerZ`) is that centre, also local.
//
// Off-diagonal terms are zero exactly when the local axes are the principal axes — true for a centred
// sphere, box, or capsule, and false the moment two such primitives are combined at an offset. Storing
// the general symmetric form rather than three principal moments is what lets primitives combine by the
// parallel-axis theorem without an eigenvalue solve.
export interface Physics3DMassData {
  mass: number;
  inertiaXX: number;
  inertiaYY: number;
  inertiaZZ: number;
  inertiaXY: number;
  inertiaXZ: number;
  inertiaYZ: number;
  centerX: number;
  centerY: number;
  centerZ: number;
}

// A rigid body: the simulated entity. Position, orientation, and velocity are flat fields rather than
// nested `Vector3`/`Quaternion` objects, so the integrator writes through them without dereferencing
// and a body array stays one contiguous block of plain numbers for the C/C++ port. `Quaternion` and
// `Matrix3` are `Entity` types backed by a `Float32Array`, which is both an indirection and a precision
// step down from what a solver's accumulators need.
//
// `index` is the body's persistent identity, assigned by the world at creation. It is what every pair
// of bodies is canonically ordered by before a contact is created, which is what keeps contact identity
// — and therefore the warm-start cache — stable while the bodies move. Geometry cannot supply that
// order, because any order derived from coordinates flips the moment those coordinates cross. Identity
// survives motion; position does not.
export interface RigidBody3D {
  index: number;
  // Once inserted, change participation through `setPhysics3DBodyType` so mass and constraints follow.
  type: Physics3DBodyType;

  // Once inserted, teleport through `setPhysics3DBodyTransform` so derived state follows.
  x: number;
  y: number;
  z: number;
  // Orientation as a UNIT quaternion. Kept normalized by the integrator, which renormalizes after every
  // angular update: integrating a quaternion by angular velocity is a first-order step off the unit
  // sphere, so without renormalization the drift compounds into a visible shear.
  orientationX: number;
  orientationY: number;
  orientationZ: number;
  orientationW: number;

  velocityX: number;
  velocityY: number;
  velocityZ: number;
  // Angular velocity in RADIANS per second, as a world-space vector whose direction is the axis and
  // whose magnitude is the rate. Radians because this is the math layer; the sync layer that copies a
  // body onto a scene node converts at that seam, which is where the SDK converts everywhere else.
  angularVelocityX: number;
  angularVelocityY: number;
  angularVelocityZ: number;

  // Prefer the apply-force/torque helpers: they reject unsupported bodies and wake accepted work.
  forceX: number;
  forceY: number;
  forceZ: number;
  torqueX: number;
  torqueY: number;
  torqueZ: number;

  mass: number;
  inverseMass: number;

  // The forward inertia tensor in the body's LOCAL frame, symmetric, six unique components, about the
  // centre of mass.
  //
  // It is stored alongside its inverse for the same reason `mass` is stored alongside `inverseMass`,
  // and for one more: the inverse is ZERO for a static, kinematic, or fixed-rotation body, so it
  // carries no information to recover the forward tensor from. Without the forward copy, making a
  // static body dynamic would have to invent an inertia — and inverting the inverse's diagonal, which
  // looks like it would work, is wrong for any tensor with off-diagonal terms.
  inertiaXX: number;
  inertiaYY: number;
  inertiaZZ: number;
  inertiaXY: number;
  inertiaXZ: number;
  inertiaYZ: number;

  // The inverse inertia tensor in the body's LOCAL frame, symmetric, six unique components. Constant
  // while the body's mass properties are.
  inverseInertiaXX: number;
  inverseInertiaYY: number;
  inverseInertiaZZ: number;
  inverseInertiaXY: number;
  inverseInertiaXZ: number;
  inverseInertiaYZ: number;

  // The same tensor rotated into WORLD space as `R * Iinv * transpose(R)`, refreshed once per substep
  // from the current orientation. It is stored rather than recomputed per constraint because every
  // contact point and every joint row multiplies by it, and a stack of a few hundred contacts would
  // otherwise redo the same similarity transform thousands of times per step.
  //
  // This field is DERIVED. Writing it has no lasting effect; write the orientation and the local tensor.
  inverseInertiaWorldXX: number;
  inverseInertiaWorldYY: number;
  inverseInertiaWorldZZ: number;
  inverseInertiaWorldXY: number;
  inverseInertiaWorldXZ: number;
  inverseInertiaWorldYZ: number;

  // The centre of mass in LOCAL space. Rarely the body's origin, and the difference is not cosmetic:
  // torque acts about the centre of mass, so a solver that rotates about the origin gives an offset
  // body the swing of a shape it does not have.
  centerX: number;
  centerY: number;
  centerZ: number;

  linearDamping: number;
  angularDamping: number;
  gravityScale: number;
  // A fixed-rotation dynamic body retains translational mass but exposes a zero inverse inertia tensor
  // to every contact and joint equation. Change this through `setPhysics3DBodyFixedRotation`.
  fixedRotation: boolean;
  // Opts a dynamic body into continuous collision detection. The discrete path remains the default;
  // change this through `setPhysics3DBodyBullet`. Honoured only once a 3D narrow phase exists to sweep
  // against — until then the flag is carried and reported, and nothing consumes it.
  bullet: boolean;

  // A sleeping body is skipped by integration and by the solver: it holds its pose, spends no
  // iterations, and its contacts contribute nothing. Sleep is decided per ISLAND rather than per body,
  // because a body resting on a moving neighbour is not at rest — the island is the unit that can
  // truthfully be called still. Static bodies are never asleep or awake; they simply do not move.
  sleeping: boolean;
  // Per-body opt-out from world sleeping. A disabled member keeps its whole connected island awake,
  // because constraints can transmit its continuing motion or external control to every neighbour.
  sleepEnabled: boolean;
  // Seconds this body has been continuously below both sleep thresholds. Reset the moment it exceeds
  // either, so the timer measures an unbroken stretch of stillness rather than a total.
  sleepTimer: number;

  // The body's collision geometry. Empty is legal and means the body is simulated but never touches
  // anything — a pure joint anchor, or a body whose shape has not been authored yet.
  colliders: Physics3DCollider[];
}

// One point of a contact, carrying the GEOMETRY AND IDENTITY of the touch and nothing about how it is
// resolved.
//
// The omission is deliberate and is the load-bearing difference from `Physics2DContactPoint`, which
// inlines `normalImpulse`, `tangentImpulse`, `normalMass`, `tangentMass`, and `bias` — every one of
// them a sequential-impulse construct. A position-based solver has no effective-mass denominators and
// no velocity bias; it accumulates a Lagrange multiplier against a compliance. Putting one solver's
// accumulators on the shared record makes the record mean "contact, as resolved by sequential
// impulses," and the second solver then either inherits dead fields or forces a breaking change.
// Solver state lives in `Physics3DContactConstraintPoint`, which the solver owns.
//
// (`x`,`y`,`z`) is the world-space contact point. (`rA*`)/(`rB*`) are the lever arms from each body's
// centre of mass to it — the vectors whose cross product with the normal is the entire reason a contact
// can produce torque. They are geometry, not solver state: every solver needs them.
//
// `featureId` is an opaque, frame-stable identifier for WHICH feature pair produced this point, so a
// solver can match this step's points against last step's accumulators and warm-start. Stability across
// steps is the whole contract; the value itself means nothing.
export interface Physics3DContactPoint {
  x: number;
  y: number;
  z: number;
  depth: number;
  featureId: number;

  rAX: number;
  rAY: number;
  rAZ: number;
  rBX: number;
  rBY: number;
  rBZ: number;
}

// A persistent contact between two bodies. Persistent is the point: the record survives between steps
// so the solver's matching accumulators can be reused.
//
// `bodyA` and `bodyB` are body indices, ALWAYS ordered so `bodyA < bodyB`. That ordering is an
// invariant of contact creation, not a convention a caller is asked to respect: a narrow phase resolves
// contact points on the reference shape's surface and ties toward its first argument, so passing the
// same pair the other way round moves the points and renumbers their feature ids.
//
// The normal points so that resolving pushes A out of B, matching the 2D package and
// `@flighthq/collision`. It is a UNIT vector; the solver builds its friction basis from it and does not
// re-normalize.
//
// `friction` and `restitution` are the combined surface values for the pair, mixed once when the
// contact is created rather than re-derived per iteration.
export interface Physics3DContact {
  bodyA: number;
  bodyB: number;
  // Indices into each body's `colliders`. Contact identity is the FOUR of these together, not the body
  // pair: two bodies touching at two separate places are two contacts with two independent warm-start
  // caches, and collapsing them onto the body pair would make each step's manifold overwrite the other's.
  colliderA: number;
  colliderB: number;

  normalX: number;
  normalY: number;
  normalZ: number;

  pointCount: number;
  points: Physics3DContactPoint[];

  friction: number;
  restitution: number;

  // Reset to true when the pair is found each step. A pre-solve hook may set it false to keep the
  // contact and its begin/end lifecycle while omitting every solver and island effect for this step.
  enabled: boolean;
  // Whether either side is a sensor: the contact is reported but generates no impulse.
  sensor: boolean;
  // Whether the pair was overlapping this step. A contact that stops touching is kept for one step so
  // an end-of-contact event can be reported before it is retired.
  touching: boolean;
}

// This step's contact transitions. A per-step output buffer, not a second record of contact state: the
// persistent contact list already knows which solid pairs are touching, and these are read off the
// moments it gains and loses entries. A CCD impact joins that same list and emits `began` at TOI, in the
// step where it happened. This includes a sensor crossing that exists only between discrete poses: its
// record persists through the impact step and emits `ended` when the next contact intake proves that the
// pair is no longer touching. The same record identity therefore spans both transitions.
export interface Physics3DContactEvents {
  began: Physics3DContact[];
  ended: Physics3DContact[];
}

// A strict per-contact callback invoked by the explicit world step. Pre-solve runs after contact
// intake and before constraint preparation, so it may adjust friction/restitution or set
// `enabled=false` for this step. A solid contact first discovered by CCD receives the same callback at
// TOI, immediately before its impact impulse; changing friction, restitution, or enabled therefore
// affects that impact. A throw from this late callback restores those override fields but leaves poses
// at TOI and retains the newly published contact/begin event — discovering the contact necessarily
// advanced the interval, so CCD cannot provide the initial intake callback's before-step exception
// boundary. Post-solve runs once the step has committed and sees both ordinary and CCD solid contacts.
// World lifecycle and body-action helpers reject calls from either hook: contact fields are the hook's
// sole mutation surface. Sensors invoke neither, because they produce no constraint to solve.
export type Physics3DContactCallback = (world: Physics3DWorld, contact: Physics3DContact) => void;

export interface Physics3DContactHooks {
  preSolve: Physics3DContactCallback | null;
  postSolve: Physics3DContactCallback | null;
}

// The sequential-impulse accumulators for one contact point. Owned by the solver, matched back to its
// `Physics3DContactPoint` by `featureId`.
//
// 3D friction needs TWO tangents, not one: the friction force spans the plane orthogonal to the normal,
// so a single tangent would leave one direction unopposed and a resting box would drift along it. The
// pair is solved as a coupled cone rather than two independent axes, because clamping each to
// `mu * normalImpulse` separately permits a combined magnitude up to `sqrt(2) * mu * normalImpulse`
// along the diagonal — a box that slides measurably faster at 45 degrees than along either axis.
export interface Physics3DContactConstraintPoint {
  featureId: number;

  normalImpulse: number;
  tangentImpulse0: number;
  tangentImpulse1: number;

  // Precomputed constraint denominators, rebuilt each substep from the lever arms and the world inverse
  // inertia tensors.
  normalMass: number;
  tangentMass0: number;
  tangentMass1: number;

  // The restitution velocity bias applied along the normal. Penetration recovery is a separate
  // position pass, so correcting overlap does not inject artificial separating velocity.
  bias: number;
}

// The solver's per-contact working set: the friction basis and the accumulators. Rebuilt each step from
// the contact list and carried across steps so warm starting has something to start from.
export interface Physics3DContactConstraint {
  // Index into `Physics3DWorld.contacts`, valid for the duration of one step.
  contact: number;

  // An orthonormal basis for the friction plane, derived from the contact normal. Derived rather than
  // stored on the contact because it is a solver's choice of parameterization, and because a basis
  // built fresh from a normal that has barely moved can flip sign between steps — which is why the
  // accumulators are matched by `featureId` and not by tangent index.
  tangent0X: number;
  tangent0Y: number;
  tangent0Z: number;
  tangent1X: number;
  tangent1Y: number;
  tangent1Z: number;

  pointCount: number;
  points: Physics3DContactConstraintPoint[];
}

// The sequential-impulse solver's own state, held by the world but owned by the solver. Keeping it here
// rather than on the contact records is what lets a second solver be added without either inheriting
// these fields or renaming them.
export interface Physics3DSequentialImpulseState {
  constraints: Physics3DContactConstraint[];
  // Constraints surviving from the previous step, keyed by the persistent contact record. A body pair
  // may have several simultaneous collider-pair contacts, so the body indices alone cannot identify
  // which accumulator belongs to which piece of compound geometry.
  constraintByContact: Map<Physics3DContact, Physics3DContactConstraint>;
}

// The knobs specific to the sequential-impulse solver.
//
// More `velocityIterations` buys accuracy in the impulse solve (stacks that do not squash); more
// `positionIterations` buys penetration recovery. `penetrationSlop` is the overlap deliberately left
// unresolved, so resting bodies stop twitching against a target of exactly zero, and
// `positionCorrection` is the fraction of the excess corrected per iteration — correcting all of it at
// once makes a deep overlap explode outward. `restitutionThreshold` is the approach speed below which
// restitution is dropped, without which a ball bounces forever at ever smaller amplitudes.
export interface Physics3DSequentialImpulseConfig {
  velocityIterations: number;
  positionIterations: number;
  penetrationSlop: number;
  positionCorrection: number;
  restitutionThreshold: number;
  warmStarting: boolean;
}

// The solver-independent knobs, plus the block belonging to whichever solver is in use.
//
// The nesting is deliberate. A flat record carrying `velocityIterations` beside `allowSleeping` would
// make every field look equally universal, and adding a position-based solver would then mean either
// dead fields on every world or a breaking rename. A named block per solver means a second solver is
// purely additive: a sibling field, and nothing above it moves.
export interface Physics3DSolverConfig {
  // Sleeping trades simulation cost for the fact that a settled stack does not need re-solving every
  // step. A body counts as still while its linear speed is under `sleepLinearThreshold` and its angular
  // speed under `sleepAngularThreshold`; the island sleeps once EVERY member has been still
  // continuously for `timeToSleep` seconds. Requiring the whole island prevents the visible failure
  // where a settled crate sleeps while the crate it leans on is still sliding out from under it.
  allowSleeping: boolean;
  sleepLinearThreshold: number;
  sleepAngularThreshold: number;
  timeToSleep: number;

  // How many equal sub-intervals each `stepPhysics3D` call is divided into. One is the default and
  // reproduces a single discrete step.
  //
  // It exists from the first release rather than being added when something needs it, because the
  // substep loop is the OUTER loop: a solver that integrates once and then iterates cannot be turned
  // into one that substeps without restructuring everything that reads the step, and every caller
  // tuning iteration counts would be retuning against a different meaning. Reserving the shape costs a
  // field and a loop that runs once.
  substeps: number;

  // Opts the world into continuous collision detection for bodies flagged `bullet`. Translation uses
  // collision's analytic convex sweep; rotation uses the separately bounded sampling path below.
  continuousCollision: boolean;
  maxCcdSubsteps: number;
  // Hard sampling budget for angular CCD. Rotation has no analytic convex sweep in the collision seam,
  // so a spinning bullet samples its pose in bounded increments and bisects the first overlapping one.
  // Zero deliberately restores linear-only CCD. The target spacing is one degree: the target is met
  // when this budget is at least `ceil(maxAngularSpeed * substepDt / (PI / 180))`; otherwise the actual
  // spacing is `maxAngularSpeed * substepDt / maxCcdRotationSubsteps`. At radius R the unsampled arc is
  // at most R times that spacing. `writePhysics3DRotationalCcdEnvelope` makes the same bound executable.
  // A feature whose entire overlap interval fits between two samples can still tunnel — bounded sampling
  // cannot promise otherwise, so authored extent is part of the guarantee rather than an implicit claim.
  maxCcdRotationSubsteps: number;

  sequentialImpulse: Physics3DSequentialImpulseConfig;
}

// The exact sampling envelope implied by one angular speed, collider radius, interval, and budget.
// `maxPointArcTravel` is an upper bound on how far the furthest point travels along its rotation arc
// between tested poses. Any angular overlap interval at least `maxAngularIncrement` wide must contain a
// sample; a narrower feature needs a larger budget. Zero samples with non-zero travel means rotational
// CCD is disabled and both maxima are positive infinity.
export interface Physics3DRotationalCcdEnvelope {
  angularTravel: number;
  sampleCount: number;
  maxAngularIncrement: number;
  maxPointArcTravel: number;
  targetIncrementMet: boolean;
}

// Pure diagnosis of whether one explicit step can run. Individual flags keep simultaneous faults
// visible; `status` is the stable summary for callers that need only a ready/not-ready branch.
// Pure diagnosis of whether a world's colliders can actually be DETECTED, which is a separate question
// from whether the step can run.
//
// The 3D narrow phase dispatches through `@flighthq/collision`'s support and face registries, so a caller
// that never called `registerBuiltInCollisionSupports3D` gets a world that steps perfectly and generates
// no contacts at all — bodies fall through floors in silence. This is how that state is told apart from a
// world where genuinely nothing is touching.
//
// `unsupportedKinds` lists the collider kinds present on some body with no registered support function,
// deduplicated and sorted so the value is stable for a given world.
export interface Physics3DCollisionExplanation {
  readonly unsupportedKinds: readonly string[];
  readonly status: 'missing-support' | 'ready';
}

export interface Physics3DStepExplanation {
  readonly bodyStateValid: boolean;
  readonly colliderStateValid: boolean;
  readonly contactStateValid: boolean;
  readonly gravityValid: boolean;
  readonly jointStateValid: boolean;
  readonly solverConfigValid: boolean;
  readonly substepsValid: boolean;
  readonly timestepValid: boolean;
  readonly velocityIterationsValid: boolean;
  readonly positionIterationsValid: boolean;
  readonly status: 'invalid-step' | 'ready';
}

// Installed by `enablePhysics3DGuards` and consulted only when `stepPhysics3D` declines its
// preconditions. It takes the world and the timestep rather than a reason, so the guard can ask
// `explainPhysics3DStep` for every simultaneous fault instead of being handed the first one.
export type Physics3DStepGuard = (world: Readonly<Physics3DWorld>, dt: number) => void;

// The diagnostics seam consulted before each contact rebuild. Installed by `enablePhysics3DGuards` and
// null otherwise, so the check and its message text are absent from a build that never enables guards.
export type Physics3DContactIntakeGuard = (world: Readonly<Physics3DWorld>) => void;

// The diagnostics seam consulted before solve islands omit unresolved joints. Installed by
// `enablePhysics3DGuards` and null otherwise, so the explanation walk and its message text are absent
// from a build that never enables guards.
export type Physics3DJointResolutionGuard = (world: Readonly<Physics3DWorld>) => void;

// Why a joint cannot be solved, or that it can. `unregistered-kind` is the common one: a joint whose
// kind has no registered solver is skipped in silence by the step, and this is how a caller finds out.
export interface Physics3DJointExplanation {
  readonly kind: Physics3DJointKind;
  readonly index: number;
  readonly hasSolver: boolean;
  readonly bodiesResolvable: boolean;
  readonly status: 'invalid-bodies' | 'solvable' | 'unregistered-kind';
}

// A joint's type identifier. A plain string, not a closed union, because joints are the family a
// physics package is most likely to be extended in: a game with a bespoke constraint (a ragdoll limit,
// a suspension with a custom profile) should be able to register its own without this package knowing.
// Built-in kinds take bare names; a user's take a vendor prefix (`acme.Suspension`), which is what
// keeps the two from colliding without a registration guard.
export type Physics3DJointKind = string;

// The fields every joint carries, whatever its kind. A concrete joint is this plus its own parameters,
// and the solver registered for its kind is what knows the difference.
//
// `bodyA` and `bodyB` are body indices ordered so `bodyA < bodyB`, for the same identity-over-geometry
// reason contacts are. The anchors are in each body's LOCAL frame.
//
// The impulse block is deliberately untyped: six accumulators, whose meaning belongs to the kind. A
// ball-and-socket means three linear components at the anchor; a hinge means those plus two angular
// rows; a 6-DOF may use all six. Only the kind knows, which is why turning them back into an impulse is
// the solver's `warmStart` rather than a generic service.
export interface Physics3DJoint {
  kind: Physics3DJointKind;
  bodyA: number;
  bodyB: number;

  localAnchorAX: number;
  localAnchorAY: number;
  localAnchorAZ: number;
  localAnchorBX: number;
  localAnchorBY: number;
  localAnchorBZ: number;

  collideConnected: boolean;

  // The load at which this joint gives way, as a FORCE and a TORQUE rather than an impulse, so a
  // threshold means the same thing at any timestep. `Infinity` — the default — is unbreakable.
  //
  // The two are read against the reaction at the ANCHOR, so they are independent: hanging a heavy body
  // off a joint loads `breakForce` and not `breakTorque`, and twisting it loads the reverse.
  breakForce: number;
  breakTorque: number;
  // Set by the step when a threshold is crossed, and never cleared by it. A broken joint constrains
  // nothing and no longer binds its two bodies into one solve island, but it stays in `world.joints`
  // until the caller removes it: deciding what a break MEANS — debris, a callback, a respawn — is the
  // caller's, and a joint that deleted itself would leave nothing to inspect.
  broken: boolean;

  impulse0: number;
  impulse1: number;
  impulse2: number;
  impulse3: number;
  impulse4: number;
  impulse5: number;

  // World-space lever arms from each body's centre of mass to its anchor, rebuilt each substep by the
  // kind's `prepare`.
  rAX: number;
  rAY: number;
  rAZ: number;
  rBX: number;
  rBY: number;
  rBZ: number;
}

// The behaviour of one joint kind. Registered per world by kind, so two worlds in one process can carry
// different custom joints without one seeing the other's.
//
// `prepare` runs once per substep, before iteration, and rebuilds whatever the kind derives from the
// current poses. `solve` runs once per velocity iteration and applies its impulses IMMEDIATELY, because
// that is what makes a sequential solver converge.
//
// `solve` TAKES `dt`, unlike the 2D package's, whose `solve(world, joint)` is velocity-level by
// construction. The parameter is what keeps a position-based or compliant solver registerable: such a
// solver's multiplier update divides its compliance by `dt` squared, so a signature without `dt` closes
// the registry to every solver that is not velocity-level. It costs one argument now and cannot be
// added later without breaking every registered kind.
//
// Neither may add or remove bodies, contacts, or joints: the solve list is fixed for the step.
export interface Physics3DJointSolver {
  prepare(world: Physics3DWorld, joint: Physics3DJoint, dt: number): void;
  solve(world: Physics3DWorld, joint: Physics3DJoint, dt: number): void;
  // Whether bodyA participates in this kind's constraint. Omit for the ordinary two-body case. A
  // one-body kind sets false so world services do not resolve, wake, remove, island-connect, or
  // suppress collisions through a placeholder endpoint the solver never reads.
  usesBodyA?: boolean;
  // Whether this constraint represents continuing external control and therefore keeps its
  // participating non-static bodies awake.
  keepsBodiesAwake?: boolean;
  // Whether this kind's two ends may be exchanged, and its chance to carry direction-bearing state
  // across the exchange. Called with the ends still in their original order; return true to let the
  // generic swap of bodies and anchors proceed, false to veto it. The generic swap can only move what
  // every joint has — two body indices and two anchors — and anything a kind measures FROM bodyA TO
  // bodyB reverses sign when the ends trade places.
  swapEnds?(joint: Physics3DJoint): boolean;
  // Writes the force and torque this kind's rows applied over the sub-interval just solved, in world
  // space at the anchor, and returns whether it could. Reading the `impulse0..5` block generically is not
  // an option: the slots mean different things per kind — three world axes for a point block, one axial
  // scalar for a distance joint — so only the kind that wrote them can say what they add up to.
  //
  // Omit it and the kind reports no reaction, `writePhysics3DJointReaction` returns false for it, and it
  // never breaks. That is the honest reading of a kind that cannot measure its own load.
  writeReaction?(joint: Readonly<Physics3DJoint>, inverseDt: number, out: Physics3DJointReaction): boolean;
  // Reapplies the impulses this joint converged on last substep, before iteration begins. Called after
  // `prepare`, so the current lever arms are in place. Omit it and the kind starts each substep cold,
  // which is correct but converges more slowly.
  warmStart?(world: Physics3DWorld, joint: Physics3DJoint): void;
  // Scales kind-specific accumulators when the caller changes timestep. The common `impulse0..5` block
  // is scaled by the step itself; a motor or another extra accumulator belongs here.
  scaleAccumulatedImpulses?(joint: Physics3DJoint, timestepRatio: number): void;
  // Discards the accumulated impulses, so a world with warm starting switched off does not keep seeding
  // each substep from a cache it has been told not to use.
  clearAccumulatedImpulses?(joint: Physics3DJoint): void;
}

// The ORIENTATION half of a joint's two attachment frames. `Physics3DJoint` carries the position half —
// the two local anchors — and a kind that constrains only a point needs nothing more. Every other kind
// needs a full frame, and this is that frame's rotation: one unit quaternion per body, taking the joint's
// own axes into that body's local frame.
//
// One convention holds across every kind that has an axis: THE JOINT'S PRIMARY AXIS IS THE FRAME'S LOCAL
// +X. A hinge spins about frame X, a slider translates along frame X, a cone-twist twists about frame X
// and swings X away from X, and a 6-DOF numbers its axes X, Y, Z in that frame. Frame Y and Z are the
// perpendicular pair a hinge measures its angle against and a cone-twist's two swing limits are named for.
//
// Fixing ONE axis for every kind is the whole point. Engines that let each joint choose (a hinge about Z,
// a cone-twist about X) make the convention a per-kind fact a reader has to carry, and a frame authored
// for one kind then means something else in another. Here a frame is a frame.
export interface Physics3DJointFrames {
  localRotationAX: number;
  localRotationAY: number;
  localRotationAZ: number;
  localRotationAW: number;
  localRotationBX: number;
  localRotationBY: number;
  localRotationBZ: number;
  localRotationBW: number;
}

// The authoring options every joint factory accepts. Anchors and `collideConnected` default, the two body
// indices do not: a joint without endpoints has no meaning to default to.
// The load a joint is carrying: the force and torque the constraint applied over one sub-interval,
// measured at the ANCHOR and expressed in world space.
//
// At the anchor rather than at the centre of mass, which is what makes the two readings independent. A
// linear constraint row acting through an offset anchor exerts `r x F` about the centre, so a torque
// measured there would rise with pure hanging load and a `breakTorque` would fire on weight alone.
//
// A FORCE, not an impulse: the solver accumulates impulses, and dividing by the sub-interval turns a
// quantity that changes with timestep into one that does not.
export interface Physics3DJointReaction {
  forceX: number;
  forceY: number;
  forceZ: number;
  torqueX: number;
  torqueY: number;
  torqueZ: number;
}

// Joints that broke during the most recent step. Drained and refilled by the step, like the contact
// events, and kept in its own record rather than widened into `Physics3DContactEvents` — that name is
// accurate and a joint break is not a contact.
export interface Physics3DJointEvents {
  broke: Physics3DJoint[];
}

export interface Physics3DJointOptions {
  bodyA: number;
  bodyB: number;
  localAnchorAX?: number;
  localAnchorAY?: number;
  localAnchorAZ?: number;
  localAnchorBX?: number;
  localAnchorBY?: number;
  localAnchorBZ?: number;
  collideConnected?: boolean;
  breakForce?: number;
  breakTorque?: number;
}

// The authoring options for a joint carrying frames. Each rotation defaults to identity, which aligns the
// joint frame with the body frame — the common case, and the one where a caller reasons in body axes.
export interface Physics3DJointFrameOptions extends Physics3DJointOptions {
  localRotationAX?: number;
  localRotationAY?: number;
  localRotationAZ?: number;
  localRotationAW?: number;
  localRotationBX?: number;
  localRotationBY?: number;
  localRotationBZ?: number;
  localRotationBW?: number;
}

// Pins two anchors together and leaves all three rotational degrees of freedom free — a shoulder, a
// pendulum link, a chain. The 3D counterpart of `Physics2DRevoluteJoint`'s point half, and the only
// built-in kind that needs no frame: with rotation unconstrained there is no axis to name.
//
// Three constraint rows, solved as a coupled 3x3 block rather than three independent axes. Solving x, then
// y, then z lets each undo part of the previous correction, and a loaded joint visibly creeps.
export type Physics3DBallAndSocketJoint = Physics3DJoint;
export type Physics3DBallAndSocketJointOptions = Physics3DJointOptions;

// Holds two anchors a distance apart along the line joining them, leaving every rotation free — a strut, a
// spring, a rope, a cable, a suspension travel. ONE row: the separation, along the unit axis between the
// anchors. The 3D counterpart of `Physics2DDistanceJoint`, widened with the travel limits a suspension and
// a cable both need.
//
// THREE BEHAVIOURS, selected by two independent flags rather than by a mode field, because each flag
// switches on one constraint row:
//
// - Neither flag: RIGID at `length`. One equality row; the strut, and the default.
// - `enableSpring`: a soft row pulling toward `length` at `frequencyHz` with `dampingRatio`. Both are
//   converted per-step against the pair's own effective mass, so a frequency means the same thing whatever
//   it is attached to and whatever timestep the world runs at.
// - `enableLimit`: one-sided rows at `minLength` and `maxLength` — the first may only push apart, the
//   second only pull together, and between them the joint does nothing at all.
//
// Enabling the limit WITHOUT the spring drops the rest-length row, which is a decision rather than an
// omission: a fixed rest length and a slack interval are contradictory demands on one axis, and the
// interval is what a rope or a cable means. Enabling both keeps the spring inside the interval, which is a
// suspension with travel stops.
export interface Physics3DDistanceJoint extends Physics3DJoint {
  length: number;

  enableSpring: boolean;
  frequencyHz: number;
  dampingRatio: number;

  enableLimit: boolean;
  minLength: number;
  maxLength: number;

  // The two limit rows' accumulators, carried across steps so a cable under sustained load warm-starts like
  // every other constraint. Non-negative MAGNITUDES, not signed coordinates: a one-sided row may only push,
  // so each is clamped at zero and its direction is carried by whichever row owns it.
  //
  // These stops are deliberately HARD, and this kind alone has no `enableLimitSpring`. Its compliance
  // already lives on the rest row as `enableSpring`, and the limits exist to bound that spring: they
  // read the UNSOFTENED effective mass precisely so a stiff spring cannot stretch through its own stop.
  // Softening them too would remove the one thing keeping `minLength` and `maxLength` meaningful.
  lowerLimitImpulse: number;
  upperLimitImpulse: number;
}

export interface Physics3DDistanceJointOptions extends Physics3DJointOptions {
  length?: number;
  enableSpring?: boolean;
  frequencyHz?: number;
  dampingRatio?: number;
  enableLimit?: boolean;
  minLength?: number;
  maxLength?: number;
}

// Pins two anchors together and locks all three rotational degrees of freedom — rigid attachment.
//
// Solved rather than exact, so it flexes under enough load. A truly rigid attachment is one body with two
// colliders; the difference is that a fixed joint can be broken at runtime.
export type Physics3DFixedJoint = Physics3DJoint & Physics3DJointFrames;
export type Physics3DFixedJointOptions = Physics3DJointFrameOptions;

// Pins two anchors together and confines relative rotation to the frame's X axis — a door, a wheel
// bearing, an elbow. Optionally motorized and angle-limited.
//
// `lowerAngle` and `upperAngle` are RADIANS, like every angle in the math layer, measured from frame A's Y
// axis to frame B's Y axis about the shared X axis, so the interval is signed and may straddle zero. The
// motor drives the relative angular velocity about that axis toward `motorSpeed`, spending at most
// `maxMotorTorque`; limits are solved after it and may override it, because a limit is a hard bound and a
// motor is a request.
export interface Physics3DHingeJoint extends Physics3DJoint, Physics3DJointFrames {
  enableLimit: boolean;
  lowerAngle: number;
  upperAngle: number;

  enableMotor: boolean;
  motorSpeed: number;
  maxMotorTorque: number;
  // The motor's own accumulator. It is kind-specific rather than part of the `impulse0..5` block because
  // the block's six slots are spoken for by the point and angular rows, and because a motor impulse is
  // scaled and cleared on its own schedule — see `scaleAccumulatedImpulses`.
  motorImpulse: number;

  // The two limit rows' accumulators, carried across steps so a limit under sustained load warm-starts
  // like every other constraint. Without them a hinge resting against its stop re-converges from zero
  // every step, and a loaded stop sags and buzzes at the exact pose it is meant to hold still.
  //
  // Non-negative MAGNITUDES, not signed coordinates: a one-sided row may only push, so each is clamped at
  // zero and its direction is carried by which row owns it. That is why `swapEnds` exchanges the two
  // without negating either, while the BOUNDS it exchanges are negated — bounds are positions on an axis
  // that reverses, these are pushes that do not.
  // A COMPLIANT limit: once the bound is crossed, the stop pushes back like a spring of
  // `limitFrequencyHz` and `limitDampingRatio` instead of arresting the coordinate outright. What a
  // ragdoll wants at the end of a joint's range and a suspension wants at the end of its travel.
  //
  // The stop stays ONE-SIDED whichever it is: softening changes how hard the row resists being crossed,
  // never whether it may pull the coordinate back the other way. A spring that could pull would be a
  // rest length, which is the distance joint's job.
  //
  // Both parameters are ignored unless `enableLimitSpring` is true and the frequency is positive, so a
  // joint that never sets them behaves exactly as a hard stop.
  enableLimitSpring: boolean;
  limitFrequencyHz: number;
  limitDampingRatio: number;
  lowerLimitImpulse: number;
  upperLimitImpulse: number;
}

export interface Physics3DHingeJointOptions extends Physics3DJointFrameOptions {
  enableLimit?: boolean;
  lowerAngle?: number;
  upperAngle?: number;
  enableMotor?: boolean;
  motorSpeed?: number;
  maxMotorTorque?: number;
  enableLimitSpring?: boolean;
  limitFrequencyHz?: number;
  limitDampingRatio?: number;
}

// Confines relative motion to translation along the frame's X axis, locking the other two translations and
// all three rotations — a piston, a lift rail, a drawer. Optionally motorized and travel-limited.
//
// `lowerTranslation` and `upperTranslation` are distances along the axis, measured from A's anchor to B's,
// so an interval containing zero admits the authored pose.
export interface Physics3DSliderJoint extends Physics3DJoint, Physics3DJointFrames {
  enableLimit: boolean;
  lowerTranslation: number;
  upperTranslation: number;

  enableMotor: boolean;
  motorSpeed: number;
  maxMotorForce: number;
  motorImpulse: number;

  // The travel stops' accumulators. Same contract as the hinge's: non-negative magnitudes, exchanged
  // rather than negated by `swapEnds`.
  // A COMPLIANT limit: once the bound is crossed, the stop pushes back like a spring of
  // `limitFrequencyHz` and `limitDampingRatio` instead of arresting the coordinate outright. What a
  // ragdoll wants at the end of a joint's range and a suspension wants at the end of its travel.
  //
  // The stop stays ONE-SIDED whichever it is: softening changes how hard the row resists being crossed,
  // never whether it may pull the coordinate back the other way. A spring that could pull would be a
  // rest length, which is the distance joint's job.
  //
  // Both parameters are ignored unless `enableLimitSpring` is true and the frequency is positive, so a
  // joint that never sets them behaves exactly as a hard stop.
  enableLimitSpring: boolean;
  limitFrequencyHz: number;
  limitDampingRatio: number;
  lowerLimitImpulse: number;
  upperLimitImpulse: number;
}

export interface Physics3DSliderJointOptions extends Physics3DJointFrameOptions {
  enableLimit?: boolean;
  lowerTranslation?: number;
  upperTranslation?: number;
  enableMotor?: boolean;
  motorSpeed?: number;
  maxMotorForce?: number;
  enableLimitSpring?: boolean;
  limitFrequencyHz?: number;
  limitDampingRatio?: number;
}

// Pins two anchors together and bounds relative rotation as a cone plus a twist — the ragdoll joint. A hip,
// a shoulder, a neck: rotation that is free within a range and hard-stopped outside it.
//
// SWING is how far frame B's X axis has tilted away from frame A's X axis, and TWIST is the remaining
// rotation about X once that tilt is removed. The two limits are independent, which is what makes this
// different from a 6-DOF with angular bounds: a cone is not a box, and a shoulder bounded by three
// per-axis intervals reaches poses along the diagonal that the anatomy does not have.
//
// `swingLimitY` and `swingLimitZ` are the maximum swing half-angles when B's X axis tilts toward frame A's
// local Y and Z respectively, in radians. Equal values give a circular cone; unequal ones give an
// elliptical cone, interpolated by the direction of the tilt. `lowerTwistAngle`/`upperTwistAngle` bound the
// twist and are signed, so a joint that may twist one way and not the other is one interval, not a flag.
export interface Physics3DConeTwistJoint extends Physics3DJoint, Physics3DJointFrames {
  enableSwingLimit: boolean;
  swingLimitY: number;
  swingLimitZ: number;

  enableTwistLimit: boolean;
  lowerTwistAngle: number;
  upperTwistAngle: number;

  // Three accumulators rather than two, because the swing limit is ONE one-sided row about whatever axis
  // the tilt is currently in — a cone has no lower bound to hold against. Same non-negative-magnitude
  // contract as the hinge's. This kind vetoes `swapEnds`, so no exchange rule is needed.
  // A COMPLIANT limit: once the bound is crossed, the stop pushes back like a spring of
  // `limitFrequencyHz` and `limitDampingRatio` instead of arresting the coordinate outright. What a
  // ragdoll wants at the end of a joint's range and a suspension wants at the end of its travel.
  //
  // The stop stays ONE-SIDED whichever it is: softening changes how hard the row resists being crossed,
  // never whether it may pull the coordinate back the other way. A spring that could pull would be a
  // rest length, which is the distance joint's job.
  //
  // Both parameters are ignored unless `enableLimitSpring` is true and the frequency is positive, so a
  // joint that never sets them behaves exactly as a hard stop.
  enableLimitSpring: boolean;
  limitFrequencyHz: number;
  limitDampingRatio: number;
  swingLimitImpulse: number;
  lowerTwistImpulse: number;
  upperTwistImpulse: number;
}

export interface Physics3DConeTwistJointOptions extends Physics3DJointFrameOptions {
  enableSwingLimit?: boolean;
  swingLimitY?: number;
  swingLimitZ?: number;
  enableTwistLimit?: boolean;
  lowerTwistAngle?: number;
  upperTwistAngle?: number;
  enableLimitSpring?: boolean;
  limitFrequencyHz?: number;
  limitDampingRatio?: number;
}

// Bounds each of the six degrees of freedom independently — the configurable joint every other kind is a
// preset of. Reach for it when no built-in kind describes the constraint, not as a default: a hinge
// expressed as a 6-DOF solves five locked rows where the hinge solves two, and reads as five coincidences
// rather than as one axis.
//
// Each axis is one of three states, encoded in its bounds rather than in a mode enum, because the bounds
// have to be read anyway and a separate flag is a second source that can disagree with them:
//
//   lower > upper   FREE      the axis is unconstrained
//   lower === upper LOCKED    held at exactly that value
//   otherwise       LIMITED   held inside [lower, upper], free within it
//
// A default-constructed joint is free on all six axes and constrains nothing. Linear bounds are distances
// along frame A's axes; angular bounds are radians about them.
export interface Physics3DGeneric6DofJoint extends Physics3DJoint, Physics3DJointFrames {
  lowerLinearX: number;
  lowerLinearY: number;
  lowerLinearZ: number;
  upperLinearX: number;
  upperLinearY: number;
  upperLinearZ: number;

  lowerAngularX: number;
  lowerAngularY: number;
  lowerAngularZ: number;
  upperAngularX: number;
  upperAngularY: number;
  upperAngularZ: number;

  // The twelve limit accumulators, as two fixed six-element arrays indexed by axis — linear X, Y, Z then
  // angular X, Y, Z, the same order the bounds above are read in. Arrays rather than twelve named fields
  // because the solver loops the axes and would otherwise need a twelve-way switch to reach a field per
  // iteration; a fixed-length array lowers to `float[6]` and keeps that loop.
  //
  // Same non-negative-magnitude contract as the hinge's. A LOCKED axis (lower === upper) is solved as an
  // equality row and uses neither.
  // A COMPLIANT limit: once the bound is crossed, the stop pushes back like a spring of
  // `limitFrequencyHz` and `limitDampingRatio` instead of arresting the coordinate outright. What a
  // ragdoll wants at the end of a joint's range and a suspension wants at the end of its travel.
  //
  // The stop stays ONE-SIDED whichever it is: softening changes how hard the row resists being crossed,
  // never whether it may pull the coordinate back the other way. A spring that could pull would be a
  // rest length, which is the distance joint's job.
  //
  // Both parameters are ignored unless `enableLimitSpring` is true and the frequency is positive, so a
  // joint that never sets them behaves exactly as a hard stop.
  enableLimitSpring: boolean;
  limitFrequencyHz: number;
  limitDampingRatio: number;
  lowerLimitImpulses: number[];
  upperLimitImpulses: number[];
}

export interface Physics3DGeneric6DofJointOptions extends Physics3DJointFrameOptions {
  lowerLinearX?: number;
  lowerLinearY?: number;
  lowerLinearZ?: number;
  upperLinearX?: number;
  upperLinearY?: number;
  upperLinearZ?: number;
  lowerAngularX?: number;
  lowerAngularY?: number;
  lowerAngularZ?: number;
  upperAngularX?: number;
  upperAngularY?: number;
  upperAngularZ?: number;
  enableLimitSpring?: boolean;
  limitFrequencyHz?: number;
  limitDampingRatio?: number;
}

// The simulation. A world owns its bodies, its contacts, its joints, and the solver state over them.
//
// It owns no broadphase index, which is the one structural difference from `Physics2DWorld`. That is
// not an omission to fill in later with a physics-specific seam: `SpatialIndexBackend2D` is the swap
// point, and its 3D counterpart does not exist yet. When it does, it attaches here exactly as the 2D
// index attaches there.
//
// `gravityX`/`gravityY`/`gravityZ` is an acceleration, scaled per body by `gravityScale`, so a balloon
// is one field rather than a special case in the integrator.
export interface Physics3DWorld {
  // Version of the serializable physics fields on this record. Runtime-owned maps and solver registries
  // are reconstructed by the caller's format layer; `hydratePhysics3DWorld` upgrades older reconstructed
  // records before they enter the explicit step path.
  version: number;

  bodies: RigidBody3D[];
  // Persistent identity lookup kept in lockstep with `bodies` by the world lifecycle helpers. Contacts
  // and joints resolve this map inside solver loops, so body identity lookup does not scale with the
  // number of bodies in the world.
  bodyByIndex: Map<number, RigidBody3D>;

  // The broadphase. The BACKEND rather than a `SpatialIndex3D`, matching `Physics2DWorld` exactly: the
  // world drives it directly, so a caller may hand over a grid, a tree, or its own implementation of the
  // seam without this package knowing which.
  index: SpatialIndexBackend3D;

  contacts: Physics3DContact[];
  joints: Physics3DJoint[];
  jointSolvers: Map<Physics3DJointKind, Physics3DJointSolver>;
  // Active two-body joints with `collideConnected=false`, indexed by canonical body pair. The nested
  // value is a reference count so removing one of several suppressing joints cannot re-enable the pair.
  jointCollisionSuppressions: Map<number, Map<number, number>>;

  events: Physics3DContactEvents;
  jointEvents: Physics3DJointEvents;
  contactHooks: Physics3DContactHooks;

  solver: Physics3DSequentialImpulseState;
  config: Physics3DSolverConfig;

  // Reusable union-find and reduction scratch for sleeping islands, allocated with the world and
  // cleared in place. Keeping them on the plain world record makes the no-per-step-allocation contract
  // explicit and maps directly to owned scratch tables in the native port.
  islandParents: Map<number, number>;
  islandSleepTimers: Map<number, number>;

  // Deterministic, flattened solve-island workspace, refilled in place after sleep has resolved the
  // active constraint graph. Each island owns contiguous slices of the body, contact, and joint index
  // arrays, so the solver never scans unrelated or sleeping constraints.
  solveIslandByRoot: Map<number, number>;
  solveIslandRoots: number[];
  solveIslandBodyStarts: number[];
  solveIslandBodyCounts: number[];
  solveIslandContactStarts: number[];
  solveIslandContactCounts: number[];
  solveIslandJointStarts: number[];
  solveIslandJointCounts: number[];
  solveIslandBodyIndices: number[];
  solveIslandContactIndices: number[];
  solveIslandJointIndices: number[];
  solveIslandCursors: number[];

  gravityX: number;
  gravityY: number;
  gravityZ: number;

  // The last successfully completed substep interval, used to express cached impulses in the next one's
  // time interval. Zero means the world has not completed a step yet.
  previousTimestep: number;

  // Monotonic counter backing `RigidBody3D.index`, so an index is never reused by a later body and a
  // stale contact can never be revived against a different body that inherited its slot.
  nextBodyIndex: number;
}

// One collider a query selected, named by the body that owns it and its position in that body's list.
//
// The INDEX travels beside the reference because it is the durable half: a collider reference is only
// valid while the body still holds it, and the index is what a caller stores to route back through
// `body.colliders` after a step.
export interface Physics3DQueryHit {
  body: RigidBody3D;
  collider: Physics3DCollider;
  colliderIndex: number;
}

// A reusable query buffer. Entries stay allocated at their HIGH-WATER MARK and only `hitCount` is
// published, so a pointer-picking loop that runs every frame allocates nothing after its first busy
// frame. Entries at or beyond `hitCount` hold stale values by design and must not be read.
export interface Physics3DQueryResult {
  hits: Physics3DQueryHit[];
  hitCount: number;
}

// Which colliders a query will consider. Category and mask select colliders whose corresponding
// authored filter field shares at least one bit; the body-type flags admit or exclude a whole class of
// body, which is how a ground-check ray ignores other characters without giving every character a
// bespoke category.
export interface Physics3DQueryFilter {
  categoryBits: number;
  maskBits: number;
  includeSensors: boolean;
  includeDynamic: boolean;
  includeKinematic: boolean;
  includeStatic: boolean;
}

// A query hit that also carries where along the ray it happened. `fraction` is in the CALLER's
// parameterization — the direction is not normalized on the way in — so a hit at `fraction` is exactly
// at `origin + direction * fraction`.
export interface Physics3DRayHit extends Physics3DQueryHit {
  fraction: number;
  x: number;
  y: number;
  z: number;
  normalX: number;
  normalY: number;
  normalZ: number;
}

export interface Physics3DRayResult {
  hits: Physics3DRayHit[];
  hitCount: number;
}

// The first collider a swept SHAPE reaches, and where.
//
// What a character controller, a camera collision probe, and a projectile with volume all need and a ray
// cannot give: a ray finds the first surface a LINE touches, so a body's shoulders pass through a gap
// its centre line clears.
//
// `hit` false leaves every other field zeroed and means the shape swept its whole displacement freely.
// `fraction` is on the same normalized [0,1] interval as `CollisionTimeOfImpact3D` — the displacement
// vector IS the sweep, so 0.25 means a quarter of the way along it, and there is no separate distance
// to reconcile against the direction's length.
//
// Only the FIRST hit is reported, where the ray queries report all of them. That is not a reduced
// version of the same feature: a ray passes THROUGH a surface and keeps going, so "the hits along it"
// is well defined, while a swept shape STOPS at first contact and everything past that point is a
// position it never reached. A caller wanting what lies beyond resolves the contact and casts again.
// `body` and `collider` are null exactly when `hit` is false. They are references rather than indices,
// matching the ray hits, so a caller acts on what it found without a second lookup — but this result is
// ONE slot rather than a list, so there is no un-published entry to leave stale and the miss has to be
// representable in the slot itself.
export interface Physics3DShapeCastResult {
  body: RigidBody3D | null;
  collider: Physics3DCollider | null;
  colliderIndex: number;
  hit: boolean;
  fraction: number;
  x: number;
  y: number;
  z: number;
  normalX: number;
  normalY: number;
  normalZ: number;
}

export type Physics3DDebugFeature = 'center-of-mass' | 'collider' | 'contact-normal' | 'joint';

// Renderer-neutral output from a physics debug query. `bodyA`/`bodyB` retain the source identities so a
// renderer can style or inspect a primitive without geometry knowing anything about colors, cameras, or
// a graphics backend. `bodyB` is -1 for a primitive sourced from one body.
export interface Physics3DDebugLine {
  feature: Physics3DDebugFeature;
  bodyA: number;
  bodyB: number;
  x0: number;
  y0: number;
  z0: number;
  x1: number;
  y1: number;
  z1: number;
}

// A sphere, where the 2D twin emits a circle. Every curved 3D collider reduces to lines plus spheres: a
// capsule is two of these joined by four lines, which is what lets a debug renderer draw the whole
// package with exactly two primitive kinds rather than one per collider kind.
export interface Physics3DDebugSphere {
  feature: Physics3DDebugFeature;
  bodyA: number;
  bodyB: number;
  x: number;
  y: number;
  z: number;
  radius: number;
}

// Arrays retain their high-water capacity; only entries below the corresponding count are live. That
// lets a caller keep one buffer and refill it every frame without allocating as the scene fluctuates.
export interface Physics3DDebugGeometry {
  lines: Physics3DDebugLine[];
  lineCount: number;
  spheres: Physics3DDebugSphere[];
  sphereCount: number;
}

export interface Physics3DDebugGeometryOptions {
  drawCentersOfMass: boolean;
  drawColliders: boolean;
  drawContacts: boolean;
  drawJoints: boolean;
  centerOfMassRadius: number;
  contactNormalLength: number;
}
