import type { BlendMode } from './BlendMode';
import type { ColorTransform } from './ColorTransform';
import type { DisplayObjectMaskHooks, DisplayObjectMaskRenderer, ScrollRectangleHooks } from './DisplayObjectRenderer';
import type { Entity } from './Entity';
import type { Matrix } from './Matrix';
import type { Renderable } from './Renderable';
import type { RenderCommandPool } from './RenderCommandPool';
import type { Renderer } from './Renderer';
import type { RenderFeatures } from './RenderFeatures';
import type { RenderNode } from './RenderNode';
import type { BitmapShader } from './Shader';

export interface RenderState extends Entity {
  allowSmoothing: boolean;
  readonly commandPool: RenderCommandPool;
  readonly backgroundColor: number;
  readonly backgroundColorRGBA: number[];
  readonly backgroundColorString: string;
  readonly currentFrameID: number;
  currentMaskDepth: number;
  readonly currentQueue: RenderNode[];
  readonly currentQueueLength: number;
  currentScrollRectangleDepth: number;
  displayObjectMaskHooks: DisplayObjectMaskHooks | null;
  scrollRectangleHooks: ScrollRectangleHooks | null;
  readonly displayObjectMaskRendererMap: Map<symbol, DisplayObjectMaskRenderer>;
  readonly displayObjectMaskRendererMapID: number;
  pixelRatio: number;
  readonly renderNodeMap: WeakMap<Renderable, RenderNode>;
  renderAlpha: number;
  renderBlendMode: BlendMode | null;
  renderColorTransform: ColorTransform | null;
  renderFeatures: RenderFeatures;
  renderShader: BitmapShader | null;
  renderTransform2D: Matrix | null;
  readonly rendererMap: Map<symbol, Renderer>;
  readonly rendererMapID: number;
  roundPixels: boolean;
  readonly tempStack: Renderable[];
}
