// GENERATED by `npm run facets` from scripts/requirement-facets.ts. DO NOT EDIT BY HAND.

export const RequirementFacet = {
  CompressionKind: 'compression.kind',
  DocumentFormat: 'document.format',
  Physics2DJointKind: 'physics2d.joint-kind',
  SceneBlendMode: 'scene.blend-mode',
  SceneMaterialKind: 'scene.material-kind',
  SceneModifierKind: 'scene.modifier-kind',
  SceneNodeKind: 'scene.node-kind',
  SceneResourceMimeType: 'scene.resource-mime-type',
  SceneShapeCommand: 'scene.shape-command',
  SceneTextureSourceKind: 'scene.texture-source-kind',
} as const;

export type RequirementFacet = (typeof RequirementFacet)[keyof typeof RequirementFacet];
