export {
  beginWgpuFrame,
  beginWgpuRenderPass,
  createSurfaceFromWgpuRenderState,
  createWgpuCanvasElement,
  createWgpuRenderState,
  createWgpuRenderTarget,
  enableWgpuBlendModeSupport,
  enableWgpuFrameCapture,
  endWgpuRenderPass,
  registerWgpuCompressedTextureDecoder,
  registerWgpuCompressedTextureUpload,
  renderWgpuBackground,
  resolveWgpuSmoothingBindGroup,
  submitWgpuRenderPass,
} from './contract';
