export {
  addMovieClipFrameScript,
  createMovieClip,
  getMovieClipCurrentFrame,
  getMovieClipCurrentLabel,
  getMovieClipTotalFrames,
  gotoAndPlayMovieClip,
  gotoAndStopMovieClip,
  isMovieClipPlaying,
  nextFrameMovieClip,
  playMovieClip,
  prevFrameMovieClip,
  setMovieClipSource,
  stopMovieClip,
  updateMovieClip,
} from './contract';
