export {
  disableTrayGuards,
  enableTrayGuards,
  createTrayIcon,
  destroyTrayIcon,
  displayTrayBalloon,
  explainTrayBackend,
  getTrayCapabilities,
  getTrayIconBounds,
  getTrayIconTitle,
  getTrayIconTooltip,
  getTrayIcons,
  isTrayDestroyed,
  isTrayIconAnimating,
  onTrayEvent,
  popupTrayContextMenu,
  removeTrayBalloon,
  setTrayIcon,
  setTrayIconContextMenu,
  setTrayIconTemplate,
  setTrayIconTitle,
  setTrayIconTooltip,
  setTrayIgnoreDoubleClickEvents,
  setTrayPressedIcon,
  startTrayIconAnimation,
  stopTrayIconAnimation,
} from './contract';
