import type { RequirementCatalogEntry } from '@flighthq/types/contract';

// Emitted in the REPOSITORY's source style, not `JSON.stringify`'s. The two differ on quoting and
// trailing commas, so a JSON-shaped file is rewritten by `npm run fix` the moment it lands and
// `catalog --check` then reports stale forever. That stayed invisible while the list was empty,
// because `[]` formats identically either way.
export function formatBuiltInRequirementCatalogSource(entries: readonly Readonly<RequirementCatalogEntry>[]): string {
  const contents = entries.length === 0 ? '[]' : `[\n${entries.map(formatEntry).join('\n')}\n]`;
  return `import type { RequirementCatalogEntry } from '@flighthq/types/contract';

// GENERATED by \`npm run catalog\` from scripts/catalog.ts. DO NOT EDIT BY HAND.
// Rows are derived from the shipped handler families, so this file restates what they claim.
export const BUILT_IN_REQUIREMENT_CATALOG_ENTRIES: readonly RequirementCatalogEntry[] = ${contents};
`;
}

function formatEntry(entry: Readonly<RequirementCatalogEntry>): string {
  const fields = Object.keys(entry)
    .sort()
    .filter((field) => (entry as unknown as Record<string, unknown>)[field] !== undefined)
    .map(
      (field) =>
        `    ${field}: '${String((entry as unknown as Record<string, unknown>)[field]).replaceAll("'", "\\'")}',`,
    );
  return `  {\n${fields.join('\n')}\n  },`;
}

export function verifyRequirementCatalogEntries(entries: readonly Readonly<RequirementCatalogEntry>[]): string[] {
  const problems: string[] = [];
  const identities = new Set<string>();
  for (const entry of entries) {
    // An ABSENT registrar is legitimate — an options-driven lane has none — but an EMPTY string is a
    // row that meant to name one and lost it, which is the typo this check exists to catch.
    for (const [field, value] of Object.entries(entry)) {
      if (value !== undefined && value.length === 0) {
        problems.push(`empty ${field}: ${requirementCatalogEntryIdentity(entry)}`);
      }
    }
    const identity = requirementCatalogEntryIdentity(entry);
    if (identities.has(identity)) problems.push(`duplicate row: ${identity}`);
    identities.add(identity);
  }
  return problems;
}

function requirementCatalogEntryIdentity(entry: Readonly<RequirementCatalogEntry>): string {
  return [entry.backend, entry.facet, entry.kind, entry.registrarImport ?? '', entry.registrarSymbol ?? ''].join(':');
}
