import type { RequirementCatalogEntry } from '@flighthq/types/contract';

export function formatBuiltInRequirementCatalogSource(entries: readonly Readonly<RequirementCatalogEntry>[]): string {
  const contents = entries.length === 0 ? '[]' : JSON.stringify(entries, null, 2);
  return `import type { RequirementCatalogEntry } from '@flighthq/types/contract';

// GENERATED by \`npm run catalog\` from scripts/catalog.ts. DO NOT EDIT BY HAND.
// Stage 4 builds the mechanism only; built-in ownership rows remain deliberately unpopulated.
export const BUILT_IN_REQUIREMENT_CATALOG_ENTRIES: readonly RequirementCatalogEntry[] = ${contents};
`;
}

export function verifyRequirementCatalogEntries(entries: readonly Readonly<RequirementCatalogEntry>[]): string[] {
  const problems: string[] = [];
  const identities = new Set<string>();
  for (const entry of entries) {
    for (const [field, value] of Object.entries(entry)) {
      if (value.length === 0) problems.push(`empty ${field}: ${requirementCatalogEntryIdentity(entry)}`);
    }
    const identity = requirementCatalogEntryIdentity(entry);
    if (identities.has(identity)) problems.push(`duplicate row: ${identity}`);
    identities.add(identity);
  }
  return problems;
}

function requirementCatalogEntryIdentity(entry: Readonly<RequirementCatalogEntry>): string {
  return [entry.backend, entry.facet, entry.kind, entry.registrarImport, entry.registrarSymbol].join(':');
}
