import type {
  RequirementBackend,
  RequirementCatalogEntry,
  RequirementDisposition,
  RequirementTranslation,
} from '@flighthq/types/contract';

// Emitted in the REPOSITORY's source style, not `JSON.stringify`'s. The two differ on quoting and
// trailing commas, so a JSON-shaped file is rewritten by `npm run fix` the moment it lands and
// `catalog --check` then reports stale forever. That stayed invisible while the list was empty,
// because `[]` formats identically either way.
export function formatBuiltInRequirementCatalogSource(
  entries: readonly Readonly<RequirementCatalogEntry>[],
  translations: readonly Readonly<RequirementTranslation>[] = [],
  backends: readonly Readonly<RequirementBackend>[] = [],
  dispositions: readonly Readonly<RequirementDisposition>[] = [],
): string {
  const contents = entries.length === 0 ? '[]' : `[\n${entries.map(formatEntry).join('\n')}\n]`;
  const translationSource =
    translations.length === 0 ? '[]' : `[\n${translations.map(formatTranslation).join('\n')}\n]`;
  const backendSource =
    backends.length === 0
      ? '[]'
      : `[\n${backends
          .map(
            (backend) =>
              `  {\n    infrastructureImport: '${backend.infrastructureImport}',\n    infrastructureSymbol: '${backend.infrastructureSymbol}',\n    name: '${backend.name}',\n  },`,
          )
          .join('\n')}\n]`;
  const dispositionSource = dispositions.length === 0 ? '[]' : `[\n${dispositions.map(formatEntry).join('\n')}\n]`;
  return `import type {
  RequirementBackend,
  RequirementCatalogEntry,
  RequirementDisposition,
  RequirementTranslation,
} from '@flighthq/types/contract';

// GENERATED by \`npm run catalog\` from scripts/catalog.ts. DO NOT EDIT BY HAND.
// Rows are derived from the shipped handler families, so this file restates what they claim.
export const BUILT_IN_REQUIREMENT_CATALOG_ENTRIES: readonly RequirementCatalogEntry[] = ${contents};

// Format-to-render implications: content needing the left requirement also needs those on the right.
export const BUILT_IN_REQUIREMENT_TRANSLATIONS: readonly RequirementTranslation[] = ${translationSource};

// What each backend needs beyond the renderers a document implies, so a generated module can compose a
// configuration that actually works rather than one that merely typechecks.
export const BUILT_IN_REQUIREMENT_BACKENDS: readonly RequirementBackend[] = ${backendSource};

// Requirements a backend deliberately does not implement, with the reason each was declined. Kept apart from
// an unresolved requirement because they mean opposite things: a gap is an oversight to report, a decline is a
// decision to record.
export const BUILT_IN_REQUIREMENT_DISPOSITIONS: readonly RequirementDisposition[] = ${dispositionSource};
`;
}

// Emitted to match how the repository's formatter prints an array of object literals: ONE element
// stays inline, two or more wrap — by element count, not line width (a 103-character two-element line
// still wraps). A generator that guessed differently would be rewritten by `npm run fix` on contact,
// leaving `catalog --check` permanently stale. Same trap the entry emitter documents.
function formatTranslation(translation: Readonly<RequirementTranslation>): string {
  const items = translation.to.map((requirement) => `{ facet: '${requirement.facet}', key: '${requirement.key}' }`);
  const to =
    items.length === 1
      ? `    to: [${items[0]}],`
      : `    to: [\n${items.map((item) => `      ${item},`).join('\n')}\n    ],`;
  return `  {\n    from: { facet: '${translation.from.facet}', key: '${translation.from.key}' },\n${to}\n  },`;
}

// Formats any FLAT row of the catalog — an entry or a disposition — in the repository's own style. Typed on
// the shape it actually needs rather than on one of its callers' types: it reads keys and scalar values and
// nothing else, and pinning it to RequirementCatalogEntry only forced a cast the moment a second row type
// appeared.
function formatEntry(entry: Readonly<Record<string, boolean | number | string | undefined>>): string {
  const fields = Object.keys(entry)
    .sort()
    .filter((field) => entry[field] !== undefined)
    .map((field) => formatField(field, formatFieldValue(entry[field])));
  return `  {\n${fields.join('\n')}\n  },`;
}

// ★ EMITS THE WRAPPED SHAPE THE FORMATTER LEAVES BEHIND, or `catalog --check` reports stale on a file
// nobody edited. A property line longer than the configured print width comes back from a `npm run fix` run
// split after the key, so a generator that always emitted one line disagrees with the formatted file
// forever. The disposition reasons are the first values long enough to reach that width.
//
// Demonstrated rather than reasoned about: with this wrapping removed, generate + fix + `catalog --check`
// reports stale, twice. An earlier probe of mine appeared to show the formatter leaving long lines alone —
// it was measuring a file `fix` had not considered changed, and I trusted it briefly. The round-trip is the
// only check that settles this, so it is the one to re-run if this ever looks unnecessary again.
function formatField(field: string, value: string): string {
  const inline = `    ${field}: ${value},`;
  if (inline.length <= FORMATTER_PRINT_WIDTH) return inline;
  return `    ${field}:\n      ${value},`;
}

// Mirrors printWidth in .oxfmtrc.json. If that moves, this moves with it or the generated file starts
// failing its own staleness check.
const FORMATTER_PRINT_WIDTH = 120;

// A number is emitted BARE. Quoting it produced `familyOrder: '3'`, which is a string where the type
// says number — the emitter had been string-only since every field was one, so the first numeric field
// would have been silently mistyped in generated source rather than rejected here.
function formatFieldValue(value: unknown): string {
  if (typeof value === 'number') return String(value);
  return `'${String(value).replaceAll("'", "\\'")}'`;
}

export function verifyRequirementCatalogEntries(entries: readonly Readonly<RequirementCatalogEntry>[]): string[] {
  const problems: string[] = [];
  const identities = new Set<string>();
  for (const entry of entries) {
    // An ABSENT registrar is legitimate — an options-driven lane has none — but an EMPTY string is a
    // row that meant to name one and lost it, which is the typo this check exists to catch.
    for (const [field, value] of Object.entries(entry)) {
      if (typeof value === 'string' && value.length === 0) {
        problems.push(`empty ${field}: ${requirementCatalogEntryIdentity(entry)}`);
      }
    }
    const identity = requirementCatalogEntryIdentity(entry);
    if (identities.has(identity)) problems.push(`duplicate row: ${identity}`);
    identities.add(identity);
  }
  return problems;
}

function requirementCatalogEntryIdentity(entry: Readonly<RequirementCatalogEntry>): string {
  return [entry.backend, entry.facet, entry.kind, entry.registrarImport ?? '', entry.registrarSymbol ?? ''].join(':');
}
