// The declared requirement-facet vocabulary. A declaration, rather than an inventory derived from
// current scene walks, can name a facet no producer emits yet. That makes an unreported facet visible
// as missing coverage instead of letting an incomplete walk redefine the denominator around itself.
//
// Run `npm run facets` to regenerate packages/types/src/RequirementFacet.ts. `npm run facets:check`
// regenerates in memory and fails on drift.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface DeclaredRequirementFacet {
  readonly id: string;
  readonly name: string;
}

// Sorted by id. The first three deliberately have no scene-kind-usage producer today: the declared
// vocabulary covers the non-render registries the program must eventually describe rather than
// deriving its scope from the six existing scene coverage walks.
const FACETS: readonly DeclaredRequirementFacet[] = [
  { id: 'compression.kind', name: 'CompressionKind' },
  { id: 'document.format', name: 'DocumentFormat' },
  { id: 'physics2d.joint-kind', name: 'Physics2DJointKind' },
  { id: 'scene.blend-mode', name: 'SceneBlendMode' },
  { id: 'scene.material-kind', name: 'SceneMaterialKind' },
  { id: 'scene.modifier-kind', name: 'SceneModifierKind' },
  { id: 'scene.node-kind', name: 'SceneNodeKind' },
  { id: 'scene.resource-mime-type', name: 'SceneResourceMimeType' },
  { id: 'scene.shape-command', name: 'SceneShapeCommand' },
  { id: 'scene.texture-source-kind', name: 'SceneTextureSourceKind' },
];

export function formatRequirementFacetSource(): string {
  const members = FACETS.map((facet) => `  ${facet.name}: '${facet.id}',`).join('\n');
  return `// GENERATED by \`npm run facets\` from scripts/requirement-facets.ts. DO NOT EDIT BY HAND.

export const RequirementFacet = {
${members}
} as const;

export type RequirementFacet = (typeof RequirementFacet)[keyof typeof RequirementFacet];
`;
}

export function verifyRequirementFacets(): string[] {
  const problems: string[] = [];
  const ids = new Set<string>();
  const names = new Set<string>();
  for (const facet of FACETS) {
    if (ids.has(facet.id)) problems.push(`duplicate id: ${facet.id}`);
    if (names.has(facet.name)) problems.push(`duplicate name: ${facet.name}`);
    ids.add(facet.id);
    names.add(facet.name);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*(?:\.[a-z0-9]+(?:-[a-z0-9]+)*)+$/.test(facet.id)) {
      problems.push(`malformed id: ${facet.id}`);
    }
    if (!/^[A-Z][A-Za-z0-9]+$/.test(facet.name)) problems.push(`malformed name: ${facet.name}`);
  }
  const sorted = FACETS.map((facet) => facet.id)
    .slice()
    .sort();
  for (let index = 0; index < FACETS.length; index++) {
    if (FACETS[index].id !== sorted[index]) {
      problems.push(`out of order at ${index}: ${FACETS[index].id} should be ${sorted[index]}`);
      break;
    }
  }
  return problems;
}

const REPO_ROOT = join(import.meta.dirname, '..');
const OUTPUT_PATH = join(REPO_ROOT, 'packages', 'types', 'src', 'RequirementFacet.ts');

function main(): void {
  const problems = verifyRequirementFacets();
  if (problems.length > 0) {
    console.error(`✗ declared requirement-facet list is malformed:\n  ${problems.join('\n  ')}`);
    process.exitCode = 1;
    return;
  }

  const source = formatRequirementFacetSource();
  if (process.argv.includes('--check')) {
    const current = readIfPresent(OUTPUT_PATH);
    if (current !== source) {
      console.error('✗ stale, run `npm run facets`:\n  packages/types/src/RequirementFacet.ts');
      process.exitCode = 1;
      return;
    }
    console.log(`OK ${FACETS.length} declared requirement facets, generated const current`);
    return;
  }

  writeFileSync(OUTPUT_PATH, source);
  console.log(`✓ wrote ${FACETS.length} declared requirement facets`);
}

function readIfPresent(path: string): string | null {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

main();
