// Generates the settled list of every import-diagnostic call site in `packages/swf`.
//
// WHY GENERATED RATHER THAN WRITTEN DOWN. The list's whole value to a downstream reader is that it is
// complete and current, and a hand-maintained list of file:line pairs is stale the first time anyone edits
// above one of them — silently, while still looking authoritative. This regenerates from the source it
// describes, so the two cannot disagree.
//
// WHAT A LINE NUMBER IS AND IS NOT. Line numbers are only meaningful at a stated commit, and the doc
// states the one it was generated from. A reader arriving later should regenerate rather than trust the
// numbers; the KIND and SEVERITY columns survive edits, the line column does not.
//
// Run `npm run capabilities:sites`.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SOURCE_DIRECTORY = join('packages', 'swf', 'src');
const OUTPUT_PATH = join('agents', 'packages', 'swf', 'diagnostic-sites.md');

interface DiagnosticSite {
  file: string;
  kind: string;
  line: number;
  severity: string;
}

const sites: DiagnosticSite[] = [];
const files = readdirSync(SOURCE_DIRECTORY)
  .filter((name) => name.endsWith('.ts') && !name.endsWith('.test.ts') && !name.includes('TestHelper'))
  .sort();

for (const name of files) {
  const lines = readFileSync(join(SOURCE_DIRECTORY, name), 'utf8').split('\n');
  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    if (!line.includes('reportImportDiagnostic(') || line.trim().startsWith('//') || line.includes('import {')) {
      continue;
    }
    const window = lines.slice(index, index + 8).join('\n');
    const severity = /ImportDiagnosticSeverity\.(\w+)/.exec(window);
    const kind = /'(swf\.[a-z0-9.-]+)'/.exec(window);
    // One site passes its kind through a variable, because the declined-tag table owns the mapping from
    // tag code to kind. Naming that rather than printing a blank keeps the row honest.
    const resolved = kind !== null ? kind[1] : /\n\s+kind,/.test(window) ? 'via SWF_DECLINED_TAG_KINDS' : 'unresolved';
    sites.push({
      file: name,
      kind: resolved,
      line: index + 1,
      severity: severity === null ? 'unresolved' : severity[1],
    });
  }
}

const bySeverity = new Map<string, number>();
for (const site of sites) bySeverity.set(site.severity, (bySeverity.get(site.severity) ?? 0) + 1);
const byFile = new Map<string, number>();
for (const site of sites) byFile.set(site.file, (byFile.get(site.file) ?? 0) + 1);

const rows = sites.map((site) => `| \`${site.file}\` | ${site.line} | ${site.severity} | \`${site.kind}\` |`);
const severitySummary = [...bySeverity.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([severity, count]) => `${severity} ${count}`)
  .join(' · ');
const fileSummary = [...byFile.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([file, count]) => `\`${file}\` ${count}`)
  .join(' · ');

const document = `---
package: '@flighthq/swf'
generated: true
---

# swf — import diagnostic call sites

**Generated by \`npm run capabilities:sites\`. Do not edit by hand.**

Every place \`packages/swf\` reports an import diagnostic, as of the commit this file was committed in.
Regenerate rather than trust the line column: **kind and severity survive edits, line numbers do not.**

**${sites.length} sites across ${byFile.size} files.** By severity: ${severitySummary}. By file: ${fileSummary}.

**A site count is not a coverage number, and the two must never be divided.** These sites and the loss
families in \`loss-path-audit.md\` are different populations that only partly intersect: most of these
predate the family work and cover none of it, and several families are covered by one site. Coverage is
stated per family in that document and derived by checking each family, never by counting sites here.

| File | Line | Severity | Kind |
| --- | --- | --- | --- |
${rows.join('\n')}
`;

writeFileSync(OUTPUT_PATH, document);
process.stdout.write(`wrote ${sites.length} diagnostic sites across ${byFile.size} files to ${OUTPUT_PATH}\n`);
