export {
  cloneMenuTemplate,
  createDefaultAppMenuTemplate,
  createDefaultEditMenuTemplate,
  createDefaultFileMenuTemplate,
  createDefaultHelpMenuTemplate,
  createDefaultViewMenuTemplate,
  createDefaultWindowMenuTemplate,
  createMenuItemTemplate,
  enableMenuSignals,
  explainMenuBackend,
  getMenuSignals,
  onMenuSelect,
  setApplicationMenu,
  showContextMenu,
  validateMenuItemTemplate,
} from './contract';
