export {
  cloneMenuTemplate,
  createDefaultAppMenuTemplate,
  createDefaultEditMenuTemplate,
  createDefaultFileMenuTemplate,
  createDefaultHelpMenuTemplate,
  createDefaultViewMenuTemplate,
  createDefaultWindowMenuTemplate,
  createMenuItemTemplate,
  attachMenuHighlight,
  attachMenuSelect,
  createMenuHighlight,
  createMenuSelect,
  destroyAppMenu,
  detachMenuHighlight,
  detachMenuSelect,
  disposeMenuHighlight,
  disposeMenuSelect,
  enableMenuSignals,
  getMenuSignals,
  setAppMenu,
  showContextMenu,
  validateMenuItemTemplate,
} from './contract';
