// Generated by `npm run wasm`; it is intentionally not committed.
import init, {
  mount_addinganimation,
  mount_addingtext,
  mount_animatedsprite,
  mount_batchloading,
  mount_bunnymark,
  mount_comparebitmapdata,
  mount_displayingabitmap,
  mount_drawingshapes,
  mount_nyancat,
  mount_piratepig,
  mount_playingsound,
  mount_playingvideo,
  mount_renderview,
  mount_sparktrail,
  mount_textmetrics,
  mount_tweenexample,
  mount_usingtilemap,
} from './wasm/drawingshapes.js';

export async function mountWasmExample(name: string): Promise<void> {
  await init();
  const mounts: Record<string, () => void> = {
    addinganimation: mount_addinganimation,
    addingtext: mount_addingtext,
    animatedsprite: mount_animatedsprite,
    batchloading: mount_batchloading,
    bunnymark: mount_bunnymark,
    comparebitmapdata: mount_comparebitmapdata,
    displayingabitmap: mount_displayingabitmap,
    drawingshapes: mount_drawingshapes,
    nyancat: mount_nyancat,
    piratepig: mount_piratepig,
    playingsound: mount_playingsound,
    playingvideo: mount_playingvideo,
    renderview: mount_renderview,
    sparktrail: mount_sparktrail,
    textmetrics: mount_textmetrics,
    tweenexample: mount_tweenexample,
    usingtilemap: mount_usingtilemap,
  };
  const mount = mounts[name];
  if (!mount) throw new Error(`No Rust/Wasm implementation for ${name}`);
  mount();
}
