// Generated by `npm run wasm`; it is intentionally not committed.
import init, { mount_drawingshapes } from './wasm/drawingshapes.js';

export async function mountWasmExample(name: string): Promise<void> {
  if (name !== 'drawingshapes') throw new Error(`No Rust/Wasm implementation for ${name}`);
  await init();
  mount_drawingshapes();
}
