export {
  applyAnimationClipToLottieDocument,
  createRiveDocumentImportResult,
  createRiveImportRegistry,
  createRiveObjectGraph,
  createScene2DFromLottieDocument,
  createScene2DFromRiveDocument,
  createScene2DFromSvgDocument,
  parseRiveDocument,
  registerAllRiveHandlers,
  registerRiveAssetHandlers,
  registerRiveClippingHandlers,
  registerRiveDrawOrderHandlers,
  registerRiveLayoutHandlers,
  registerRivePaintHandlers,
  registerRivePathHandlers,
  registerRiveShapeHandlers,
  registerRiveSkeletonHandlers,
  registerRiveSoloHandlers,
  registerRiveStateMachineHandlers,
  registerRiveTextHandlers,
} from './contract';
