import type BitmapFilter from '../filters/BitmapFilter.js';
import type Affine2D from '../math/Affine2D.js';
import type Rectangle from '../math/Rectangle.js';
import type BlendMode from './BlendMode.js';
import type DirtyFlags from './DirtyFlags.js';
import type DisplayObjectContainer from './DisplayObjectContainer.js';
import type { DisplayObjectSymbols as $ } from './DisplayObjectSymbols.js';
import type LoaderInfo from './LoaderInfo.js';
import type Shader from './Shader.js';
import type Stage from './Stage.js';
import type Transform from './Transform.js';

export default interface DisplayObject {
  [$.alpha]: number;
  [$.blendMode]: BlendMode;
  [$.bounds]: Rectangle;
  [$.cacheAsBitmap]: boolean;
  [$.cacheAsBitmapMatrix]: Affine2D | null;
  [$.children]: DisplayObject[] | null;
  [$.dirtyFlags]: DirtyFlags;
  [$.filters]: BitmapFilter[] | null;
  [$.height]: number;
  [$.loaderInfo]: LoaderInfo | null;
  [$.localBounds]: Rectangle;
  [$.localBoundsID]: number;
  [$.localTransform]: Affine2D;
  [$.localTransformID]: number;
  [$.mask]: DisplayObject | null;
  [$.maskedObject]: DisplayObject | null;
  [$.name]: string | null;
  [$.opaqueBackground]: number | null;
  [$.parent]: DisplayObjectContainer | null;
  [$.parentTransformID]: number;
  [$.root]: DisplayObjectContainer | null;
  [$.rotationAngle]: number;
  [$.rotationCosine]: number;
  [$.rotationSine]: number;
  [$.scale9Grid]: Rectangle | null;
  [$.scaleX]: number;
  [$.scaleY]: number;
  [$.scrollRect]: Rectangle | null;
  [$.shader]: Shader | null;
  [$.stage]: Stage | null;
  [$.transform]: Transform | null;
  [$.width]: number;
  [$.worldBounds]: Rectangle;
  [$.worldTransform]: Affine2D;
  [$.worldTransformID]: number;
  [$.visible]: boolean;
  [$.x]: number;
  [$.y]: number;
}
